/**
 * Legacy Key Map – includes origination fee currency field mappings
 * 
 * Maps legacy dot-notation field keys (used in fieldKeyMap.ts and SectionContent files)
 * to actual DB field_dictionary field_key values (br_p_firstName convention).
 * 
 * This translation layer ensures data persistence works without requiring
 * a massive refactor of 30+ UI files that use the legacy dot-notation convention.
 * 
 * The map is used by useDealFields.ts during save/load to resolve field_dictionary entries.
 */

export const LEGACY_TO_DB_KEY: Record<string, string> = {
  // ──────────────────────────────────────────────────
  // BORROWER PRIMARY
  // ──────────────────────────────────────────────────
  'borrower.borrower_type': 'br_p_borrowerType',
  'borrower.borrower_id': 'br_p_borrowerId',
  'borrower.full_name': 'br_p_fullName',
  'borrower.first_name': 'br_p_firstName',
  'borrower.middle_initial': 'br_p_middleInitia',
  'borrower.last_name': 'br_p_lastName',
  'borrower.capacity': 'br_p_capacity',
  'borrower.email': 'br_p_emailAddres',
  'borrower.credit_score': 'br_p_creditScore',
  'borrower.issue_1098': 'br_p_issue1098',
  'borrower.alternate_reporting': 'br_p_alternatReport',
  'borrower.tax_id_type': 'br_p_taxIdType',
  'borrower.tin': 'br_p_tin',
  'borrower.tin_verified': 'br_p_tinVerifi',
  'borrower.is_primary': 'br_p_isPrimar',
  'borrower.address.street': 'br_p_address',
  'borrower.address.city': 'br_p_borrowerCity',
  'borrower.state': 'br_p_state2',
  'borrower.address.zip': 'br_p_zip',
  'borrower.mailing_same_as_primary': 'br_p_mailingSameAsPrimar',
  'borrower.mailing.street': 'br_p_mailingStreet',
  'borrower.mailing.city': 'br_p_mailingCity',
  'borrower.mailing.state': 'br_p_mailingState',
  'borrower.mailing.zip': 'br_p_mailingZip',
  'borrower.phone.home': 'br_p_homePhone',
  'borrower.phone.work': 'br_p_workPhone',
  'borrower.phone.mobile': 'br_p_cellPhone',
  'borrower.phone.fax': 'br_p_fax',
  'borrower.preferred.home': 'br_p_preferreHome',
  'borrower.preferred.work': 'br_p_preferreWork',
  'borrower.preferred.cell': 'br_p_preferreCell',
  'borrower.preferred.fax': 'br_p_preferreFax',
  'borrower.delivery_print': 'br_p_deliveryPrint',
  'borrower.delivery_email': 'br_p_deliveryEmail',
  'borrower.delivery_sms': 'br_p_deliverySms',
  'borrower.delivery_online': 'br_p_deliveryOnline',
  'borrower.delivery_mail': 'br_p_deliveryMail',
  'borrower.send_payment_notification': 'br_p_sendPaymenNotifi',
  'borrower.send_late_notice': 'br_p_sendLateNotice',
  'borrower.send_borrower_statement': 'br_p_sendBorrowStatem',
  'borrower.send_maturity_notice': 'br_p_sendMaturiNotice',
  'borrower.vesting': 'br_p_vestin',
  'borrower.ford.1': 'br_p_ford1',
  'borrower.ford.2': 'br_p_ford2',
  'borrower.ford.3': 'br_p_ford3',
  'borrower.ford.4': 'br_p_ford4',
  'borrower.ford.5': 'br_p_ford5',
  'borrower.ford.6': 'br_p_ford6',
  'borrower.ford.7': 'br_p_ford7',
  'borrower.ford.8': 'br_p_ford8',
  'borrower.note': 'br_p_note',
  'borrower.description': 'br_p_borrowerDescri',

  // BORROWER AUTHORIZED PARTY
  'borrower.authorized_party.first_name': 'br_p_authPartyFirstName',
  'borrower.authorized_party.middle_name': 'br_p_authPartyMiddleName',
  'borrower.authorized_party.last_name': 'br_p_authPartyLastName',
  'borrower.authorized_party.capacity': 'br_p_authPartyCapaci',
  'borrower.authorized_party.email': 'br_p_authPartyEmail',
  'borrower.authorized_party.address.street': 'br_p_authPartyStreet',
  'borrower.authorized_party.address.city': 'br_p_authPartyCity',
  'borrower.authorized_party.address.state': 'br_p_authPartyState',
  'borrower.authorized_party.address.zip': 'br_p_authPartyZip',
  'borrower.authorized_party.phone.home': 'br_p_authPartyHomePhone',
  'borrower.authorized_party.phone.work': 'br_p_authPartyWorkPhone',
  'borrower.authorized_party.phone.cell': 'br_p_authPartyCellPhone',
  'borrower.authorized_party.phone.fax': 'br_p_authPartyFax',
  'borrower.authorized_party.send_pref.payment_notification': 'br_p_authPartySendPaymen',
  'borrower.authorized_party.send_pref.late_notice': 'br_p_authPartySendLate',
  'borrower.authorized_party.send_pref.borrower_statement': 'br_p_authPartySendBorrow',
  'borrower.authorized_party.send_pref.maturity_notice': 'br_p_authPartySendMaturi',
  'borrower.authorized_party.delivery.email': 'br_p_authPartyDeliveEmail',
  'borrower.authorized_party.delivery.mail': 'br_p_authPartyDeliveMail',
  'borrower.authorized_party.delivery.sms': 'br_p_authPartyDeliveSms',
  'borrower.authorized_party.details': 'br_p_authPartyDetail',

  // BORROWER BANKING (ACH)
  'ach.bank_name': 'br_p_bankName',
  'ach.bank_address': 'br_p_bankAddres',
  'ach.routing_number': 'br_p_routingNumber',
  'ach.account_number': 'br_p_accountNumber',
  'ach.individual_id': 'br_p_individId',
  'ach.individual_name': 'br_p_individName',
  'ach.account_type': 'br_p_accountType',
  'ach.service_status': 'br_p_serviceStatus',
  'ach.apply_debit_as': 'br_p_applyDebitAs',
  'ach.debit_frequency': 'br_p_debitFreque',
  'ach.debit_due_day': 'br_p_debitDueDay',
  'ach.next_debit_date': 'br_p_nextDebitDate',
  'ach.stop_date': 'br_p_stopDate',
  'ach.debit_amount': 'br_p_debitAmount',
  'ach.send_confirm': 'br_p_sendConfir',
  'ach.disable_online_payment': 'br_p_disableOnlinePaymen',
  'ach.notes': 'br_b_notes',

  // BORROWER TAX DETAIL (1098)
  'borrower.1098.designated_recipient': 'br_t_designatRecipi',
  'borrower.1098.name': 'br_t_name',
  'borrower.1098.address': 'br_t_address',
  'borrower.1098.account_number': 'br_t_accountNumber',
  'borrower.1098.city': 'br_t_city',
  'borrower.1098.tin_type': 'br_t_tinType',
  'borrower.1098.tin': 'br_t_tin',
  'borrower.1098.state': 'br_t_state',
  'borrower.1098.zip': 'br_t_zip',
  'borrower.1098.send_1098': 'br_p_send1098',

  // BORROWER GUARANTOR
  'borrower.guarantor.borrower_type': 'br_p_guarantoBorrowType',
  'borrower.guarantor.borrower_id': 'br_p_guarantoBorrowId',
  'borrower.guarantor.full_name': 'br_p_guarantoFullName',
  'borrower.guarantor.first_name': 'br_p_guarantoFirstName',
  'borrower.guarantor.middle_initial': 'br_p_guarantoMiddleInitia',
  'borrower.guarantor.last_name': 'br_p_guarantoLastName',
  'borrower.guarantor.capacity': 'br_p_guarantoCapaci',
  'borrower.guarantor.email': 'br_p_guarantoEmail',
  'borrower.guarantor.credit_score': 'br_p_guarantoCreditScore',
  'borrower.guarantor.issue_1098': 'br_p_guarantoIssue1098',
  'borrower.guarantor.alternate_reporting': 'br_p_guarantoAlternReport',
  'borrower.guarantor.tax_id_type': 'br_p_guarantoTaxIdType',
  'borrower.guarantor.tin': 'br_p_guarantoTaxId',
  'borrower.guarantor.tin_verified': 'br_p_guarantoTinVerifi',
  'borrower.guarantor.address.street': 'br_p_guarantoStreet',
  'borrower.guarantor.address.city': 'br_p_guarantoCity',
  'borrower.guarantor.state': 'br_p_guarantoState',
  'borrower.guarantor.address.zip': 'br_p_guarantoZip',
  'borrower.guarantor.mailing_same_as_primary': 'br_p_guarantoMailinSameAs',
  'borrower.guarantor.mailing.street': 'br_p_guarantoMailinStreet',
  'borrower.guarantor.mailing.city': 'br_p_guarantoMailinCity',
  'borrower.guarantor.mailing.state': 'br_p_guarantoMailinState',
  'borrower.guarantor.mailing.zip': 'br_p_guarantoMailinZip',
  'borrower.guarantor.phone.home': 'br_p_guarantoHomePhone',
  'borrower.guarantor.phone.work': 'br_p_guarantoWorkPhone',
  'borrower.guarantor.phone.mobile': 'br_p_guarantoCellPhone',
  'borrower.guarantor.phone.fax': 'br_p_guarantoFax',
  'borrower.guarantor.preferred.home': 'br_p_guarantoPreferHome',
  'borrower.guarantor.preferred.work': 'br_p_guarantoPreferWork',
  'borrower.guarantor.preferred.cell': 'br_p_guarantoPreferCell',
  'borrower.guarantor.preferred.fax': 'br_p_guarantoPreferFax',
  'borrower.guarantor.delivery_print': 'br_p_guarantoDelivePrint',
  'borrower.guarantor.delivery_email': 'br_p_guarantoDeliveEmail',
  'borrower.guarantor.delivery_sms': 'br_p_guarantoDeliveSms',
  'borrower.guarantor.send_payment_notification': 'br_p_guarantoSendPaymen',
  'borrower.guarantor.send_late_notice': 'br_p_guarantoSendLate',
  'borrower.guarantor.send_borrower_statement': 'br_p_guarantoSendBorrow',
  'borrower.guarantor.send_maturity_notice': 'br_p_guarantoSendMaturi',
  'borrower.guarantor.delivery_online': 'br_p_guarantoDeliveOnline',
  'borrower.guarantor.delivery_mail': 'br_p_guarantoDeliveMail',
  'borrower.guarantor.vesting': 'br_p_guarantoVestin',
  'borrower.guarantor.vesting_overridden': 'br_p_guarantoVestinOverri',
  'borrower.guarantor.ford.1': 'br_p_guarantoFord1',
  'borrower.guarantor.ford.2': 'br_p_guarantoFord2',
  'borrower.guarantor.ford.3': 'br_p_guarantoFord3',
  'borrower.guarantor.ford.4': 'br_p_guarantoFord4',
  'borrower.guarantor.ford.5': 'br_p_guarantoFord5',
  'borrower.guarantor.ford.6': 'br_p_guarantoFord6',
  'borrower.guarantor.ford.7': 'br_p_guarantoFord7',
  'borrower.guarantor.ford.8': 'br_p_guarantoFord8',

  // ──────────────────────────────────────────────────
  // CO-BORROWER
  // ──────────────────────────────────────────────────
  'coborrower.full_name': 'cb_p_coborrowFullName',
  'coborrower.first_name': 'cb_p_coborrowFirstName',
  'coborrower.middle_name': 'cb_p_coborrowMiddleName',
  'coborrower.last_name': 'cb_p_coborrowLastName',
  'coborrower.salutation': 'cb_p_coborrowSaluta',
  'coborrower.generation': 'cb_p_coborrowGenera',
  'coborrower.email': 'cb_p_coborrowEmail',
  'coborrower.phone.home': 'cb_p_coborrowHomePhone',
  'coborrower.phone.work': 'cb_p_coborrowWorkPhone',
  'coborrower.phone.mobile': 'cb_p_coborrowCellPhone',
  'coborrower.fax': 'cb_p_coborrowFax',
  'coborrower.preferred.home': 'cb_p_preferreHome',
  'coborrower.preferred.work': 'cb_p_preferreWork',
  'coborrower.preferred.cell': 'cb_p_preferreCell',
  'coborrower.preferred.fax': 'cb_p_preferreFax',
  'coborrower.address.street': 'cb_p_coborrowStreet',
  'coborrower.address.city': 'cb_p_coborrowCity',
  'coborrower.state': 'cb_p_coborrowState',
  'coborrower.address.zip': 'cb_p_coborrowZip',
  'coborrower.primary_address.street': 'cb_p_primaryAddresStreet',
  'coborrower.primary_address.city': 'cb_p_primaryAddresCity',
  'coborrower.primary_address.state': 'cb_p_primaryAddresState',
  'coborrower.primary_address.zip': 'cb_p_primaryAddresZip',
  'coborrower.mailing_address.street': 'cb_p_mailingAddresStreet',
  'coborrower.mailing_address.city': 'cb_p_mailingAddresCity',
  'coborrower.mailing_address.state': 'cb_p_mailingAddresState',
  'coborrower.mailing_address.zip': 'cb_p_mailingAddresZip',
  'coborrower.mailing_same_as_primary': 'cb_p_sameAsPrimar',
  'coborrower.is_primary': 'cb_p_primaryContac',
  'coborrower.loan_number': 'cb_p_loanNumber',
  'coborrower.tin': 'cb_p_tin',
  'coborrower.relation': 'cb_p_relation',
  'coborrower.type': 'cb_p_borrowerType',
  'coborrower.borrower_id': 'cb_p_borrowerId',
  'coborrower.borrower_type': 'cb_p_borrowerType2',
  'coborrower.capacity': 'cb_p_capacity',
  'coborrower.credit_score': 'cb_p_creditScore',
  'coborrower.vesting': 'cb_p_vestin',
  'coborrower.ford': 'cb_p_ford',
  'coborrower.ford1': 'cb_p_ford1',
  'coborrower.ford2': 'cb_p_ford2',
  'coborrower.ford3': 'cb_p_ford3',
  'coborrower.ford4': 'cb_p_ford4',
  'coborrower.ford5': 'cb_p_ford5',
  'coborrower.ford6': 'cb_p_ford6',
  'coborrower.ford7': 'cb_p_ford7',
  'coborrower.ford8': 'cb_p_ford8',
  'coborrower.issue_1098': 'cb_p_issue1098',
  'coborrower.alternate_reporting': 'cb_p_alternatReport',
  'coborrower.delivery_online': 'cb_p_deliveryOnline',
  'coborrower.delivery_mail': 'cb_p_deliveryMail',
  'coborrower.dob': 'cb_p_dob',
  'coborrower.credit_reporting': 'cb_p_creditReportEnable',
  'coborrower.res_code': 'cb_p_coborrowResCode',
  'coborrower.address_indicator': 'cb_p_coborrowAddresIndica',
  'coborrower.send_borrower_notifications': 'cb_p_sendBorrowNotifi',
  'coborrower.format': 'cb_p_coborrowEmailFormat',
  'coborrower.delivery_print': 'cb_p_coborrowDelivePrint',
  'coborrower.delivery_email': 'cb_p_coborrowDeliveEmail',
  'coborrower.delivery_sms': 'cb_p_coborrowDeliveSms',
  'coborrower.tax_id_type': 'cb_p_taxIdType',
  'coborrower.tin_verified': 'cb_p_tinVerifi',
  'coborrower.send_payment_notification': 'cb_p_sendPaymenNotifi',
  'coborrower.send_late_notice': 'cb_p_sendLateNotice',
  'coborrower.send_borrower_statement': 'cb_p_sendBorrowStatem',
  'coborrower.send_maturity_notice': 'cb_p_sendMaturiNotice',
  'coborrower.parent_borrower_prefix': 'cb_p_parentBorrowPrefix',

  // CO-BORROWER BANKING
  'coborrower.bank.name': 'cb_p_coborrowBankName',
  'coborrower.bank.routing_number': 'cb_p_coborrowRoutinNumber',
  'coborrower.bank.account_number': 'cb_p_coborrowAccounNumber',
  'coborrower.bank.account_holder': 'cb_p_coborrowAccounHolder',
  'coborrower.bank.account_type': 'cb_p_coborrowAccounType',
  'coborrower.bank.address.street': 'cb_p_coborrowBankStreet',
  'coborrower.bank.address.city': 'cb_p_coborrowBankCity',
  'coborrower.bank.address.state': 'cb_p_coborrowBankState',
  'coborrower.bank.address.zip': 'cb_p_coborrowBankZip',
  'coborrower.bank.phone': 'cb_p_coborrowBankPhone',

  // CO-BORROWER TAX DETAIL
  'coborrower.tax_id': 'cb_p_taxId',
  'coborrower.tax.filing_status': 'cb_p_coborrowFilingStatus',
  'coborrower.tax.exempt': 'cb_p_coborrowTaxExempt',
  'coborrower.tax.year': 'cb_p_coborrowTaxYear',
  'coborrower.tax.annual_income': 'cb_p_coborrowAnnualIncome',
  'coborrower.tax.bracket': 'cb_p_coborrowTaxBracke',
  'coborrower.tax.notes': 'cb_p_coborrowTaxNotes',

  // CO-BORROWER NOTE
  'coborrower.note': 'cb_p_note',

  // ──────────────────────────────────────────────────
  // LENDER INFO
  // ──────────────────────────────────────────────────
  'lender.type': 'ld_p_lenderType',
  'lender.lender_id': 'ld_p_lenderId',
  'lender.full_name': 'ld_p_fullName',
  'lender.first_name': 'ld_p_firstName',
  'lender.middle_name': 'ld_p_middleName',
  'lender.last_name': 'ld_p_lastName',
  'lender.capacity': 'ld_p_capacity',
  'lender.email': 'ld_p_email',
  'lender.tax_id_type': 'ld_p_taxIdType',
  'lender.tax_id': 'ld_p_taxId',
  'lender.issue_1099': 'ld_p_issue1099',
  'lender.prepare_ca_881': 'ld_p_prepareCa881',
  'lender.taxed_as': 'ld_p_taxedAs',
  'lender.lp_lllp_llc_taxed_as_corp': 'ld_p_lpLllpLlcTaxedAsCorp',
  'lender.tin_verified': 'ld_p_tinVerifi',
  'lender.alternate_reporting': 'ld_p_alternatReport',
  'lender.is_primary': 'ld_p_isPrimar',
  'lender.isPrimary': 'ld_p_isPrimar',
  'lender.primary_address.street': 'ld_p_street',
  'lender.primary_address.city': 'ld_p_city',
  'lender.primary_address.state': 'ld_p_state',
  'lender.primary_address.zip': 'ld_p_zip',
  'lender.phone.home': 'ld_p_homePhone',
  'lender.phone.work': 'ld_p_workPhone',
  'lender.phone.cell': 'ld_p_cellPhone',
  'lender.phone.fax': 'ld_p_fax',
  'lender.send_pref.payment_notification': 'ld_p_paymentNotifi',
  'lender.send_pref.late_notice': 'ld_p_lateNotice',
  'lender.send_pref.borrower_statement': 'ld_p_borrowerStatem',
  'lender.send_pref.maturity_notice': 'ld_p_maturityNotice',
  'lender.preferred.home': 'ld_p_preferreHome',
  'lender.preferred.work': 'ld_p_preferreWork',
  'lender.preferred.cell': 'ld_p_preferreCell',
  'lender.preferred.fax': 'ld_p_preferreFax',
  'lender.care_of.street': 'ld_p_careOfStreet',
  'lender.care_of.city': 'ld_p_careOfCity',
  'lender.care_of.state': 'ld_p_careOfState',
  'lender.care_of.zip': 'ld_p_careOfZip',
  'lender.vesting': 'ld_p_vestin',
  'lender.ford.1': 'ld_p_ford1',
  'lender.ford.2': 'ld_p_ford2',
  'lender.ford.3': 'ld_p_ford3',
  'lender.ford.4': 'ld_p_ford4',
  'lender.ford.5': 'ld_p_ford5',
  'lender.ford.6': 'ld_p_ford6',
  'lender.ford.7': 'ld_p_ford7',
  'lender.ford.8': 'ld_p_ford8',
  'lender.loan_id': 'ld_p_loanId',
  'lender.loan_type': 'ld_p_loanType',
  'lender.delivery.print': 'ld_p_deliveryPrint',
  'lender.delivery.email': 'ld_p_deliveryEmailLender',
  'lender.delivery.sms': 'ld_p_deliverySmsLender',
  'lender.dob': 'ld_p_dob',
  'lender.mailing.street': 'ld_p_mailingStreet',
  'lender.mailing.city': 'ld_p_mailingCity',
  'lender.mailing.state': 'ld_p_mailingState',
  'lender.mailing.zip': 'ld_p_mailingZip',
  'lender.mailing_same_as_primary': 'ld_p_mailingSameAsPrimar',
  'lender.servicing_agreement_on_file': 'ld_p_servicinAgreem',
  'lender.freeze_outgoing_disbursements': 'ld_p_freezeOutgoi',
  'lender.investor_questionnaire_due': 'ld_p_investoQuesti',
  'lender.investor_questionnaire_due_date': 'ld_p_investoQuestiDueDate',

  // LENDER AUTHORIZED PARTY
  'lender.authorized_party.first_name': 'ld_ap_firstName',
  'lender.authorized_party.middle_name': 'ld_ap_middleName',
  'lender.authorized_party.last_name': 'ld_ap_lastName',
  'lender.authorized_party.capacity': 'ld_ap_authorizPartyCapaci',
  'lender.authorized_party.email': 'ld_ap_email',
  'lender.authorized_party.send_pref.payment_notification': 'ld_ap_paymentNotifi',
  'lender.authorized_party.send_pref.late_notice': 'ld_ap_lateNotice',
  'lender.authorized_party.send_pref.maturity_notice': 'ld_ap_maturityNotice',
  'lender.authorized_party.send_pref.borrower_statement': 'ld_ap_borrowerStatem',
  'lender.authorized_party.address.street': 'ld_ap_street',
  'lender.authorized_party.address.city': 'ld_ap_city',
  'lender.authorized_party.address.state': 'ld_ap_state',
  'lender.authorized_party.address.zip': 'ld_ap_zip',
  'lender.authorized_party.address.details': 'ld_ap_authorizPartyAddresDetail',
  'lender.authorized_party.phone.home': 'ld_ap_homePhone',
  'lender.authorized_party.phone.work': 'ld_ap_workPhone',
  'lender.authorized_party.phone.cell': 'ld_ap_cellPhone',
  'lender.authorized_party.phone.fax': 'ld_ap_fax',
  'lender.authorized_party.delivery.email': 'ld_ap_deliveryEmail',
  'lender.authorized_party.delivery.mail': 'ld_ap_deliveryMail',
  'lender.authorized_party.delivery.sms': 'ld_ap_deliverySms',

  // LENDER BANKING
  'lender.banking.ach_status': 'ld_p_achStatus',
  'lender.banking.bank': 'ld_p_bank',
  'lender.banking.routing_number': 'ld_b_routingNumber',
  'lender.banking.account_number': 'ld_p_accountNumber',
  'lender.banking.account_type': 'ld_p_accountType',
  'lender.banking.account_name': 'ld_p_accountName',
  'lender.banking.account_id': 'ld_p_accountId',
  'lender.banking.further_credit_to': 'ld_p_furtherCreditTo',
  'lender.banking.by_check': 'ld_p_byCheck',
  'lender.banking.check_same_as_mailing': 'ld_p_checkSameAsMailing',
  'lender.banking.address': 'ld_p_checkAddres',
  'lender.banking.city': 'ld_p_checkCity',
  'lender.banking.zip_code': 'ld_p_checkZip',
  'lender.banking.ach_email': 'ld_p_achEmail',
  'lender.banking.ach_email_2': 'ld_p_achEmail2',
  'lender.banking.cc_name': 'ld_p_creditCardName',
  'lender.banking.cc_number': 'ld_p_cardNumber',
  'lender.banking.cc_security_code': 'ld_p_securityCode',
  'lender.banking.cc_expiration': 'ld_p_expirati',
  'lender.banking.cc_zip': 'ld_p_creditCardZip',

  // LENDER TAX INFO
  'lender.tax_payer.designated_recipient': 'ld_p_designatRecipi',
  'lender.tax_payer.name': 'ld_p_taxPayerName',
  'lender.tax_payer.street_address': 'ld_p_taxPayerStreetAddres',
  'lender.tax_payer.account_number': 'ld_b_taxPayerAccounNumber',
  'lender.tax_payer.city': 'ld_p_taxPayerCity',
  'lender.tax_payer.recipient_type': 'ld_p_taxPayerRecipiType',
  'lender.tax_payer.ssn': 'ld_p_taxPayerSsn',
  'lender.tax_payer.state': 'ld_p_taxPayerState',
  'lender.tax_payer.zip_code': 'ld_p_taxPayerZipCode',
  'lender.tax_payer.auto_synchronize': 'ld_p_taxPayerAutoSynchr',

  // ──────────────────────────────────────────────────
  // LOAN TERMS
  // ──────────────────────────────────────────────────
  'loan_terms.loan_amount': 'ln_p_loanAmount',
  'loan.original_amount': 'ln_p_originalAmount',
  'loan_terms.note_rate': 'ln_p_noteRate',
  'loan_terms.sold_rate': 'ln_p_soldRate',
  'loan_terms.sold_rate_enabled': 'ln_p_soldRateEnable',
  'loan_terms.sold_rate_originating_vendor': 'ln_p_soldRateOriginatingVendor',
  'loan_terms.sold_rate_company': 'ln_p_soldRateCompany',
  'loan_terms.sold_rate_other_client_1': 'ln_p_soldRateOtherClient1',
  'loan_terms.sold_rate_other_client_2': 'ln_p_soldRateOtherClient2',
  'loan_terms.interest_split': 'ln_p_interestSplit',
  'loan_terms.interest_split_enabled': 'ln_p_interestSplitEnable',
  'loan_terms.accrual_method': 'ln_p_accrualMethod',
  'loan_terms.unearned_discount_balance': 'ln_p_unearnedDiscouBalanc',
  'loan_terms.prepaid_payments': 'ln_p_prepaidPaymen',
  'loan_terms.prepaid_payments_enabled': 'ln_p_prepaidPaymenEnable',
  'loan_terms.prepaid_payments_months': 'ln_p_prepaidPaymenMonths',
  'loan_terms.impounded_payments': 'ln_p_impoundePaymen',
  'loan_terms.impounded_payments_enabled': 'ln_p_impoundePaymenEnable',
  'loan_terms.impounded_payments_months': 'ln_p_impoundePaymenMonths',
  'loan_terms.funding_holdback': 'ln_p_fundingHoldba',
  'loan_terms.funding_holdback_enabled': 'ln_p_fundingHoldbaEnable',
  'loan_terms.funding_holdback_held_by': 'ln_p_fundingHoldbaHeldBy',
  'loan_terms.funding_records': 'ln_p_fundingRecord',
  'loan_terms.funding_history': 'ln_p_fundingHistor',
  'loan_terms.number_of_payments': 'ln_p_numberOfPaymen',
  'loan_terms.payment_frequency': 'ln_p_paymentFreque',
  'loan_terms.amortized_partially': 'ln_p_amortizedPartially',
  'loan_terms.amortized': 'ln_p_amortized',
  'loan_terms.payment_monthly': 'ln_p_paymentMonthly',
  'loan_terms.payment_weekly': 'ln_p_paymentWeekly',
  'loan_terms.day_due': 'ln_p_dayDue',
  'loan_terms.first_payment': 'ln_p_firstPaymen',
  'loan_terms.last_payment_received': 'ln_p_lastPaymenReceiv',
  'loan_terms.paid_to': 'ln_p_paidTo',
  'loan_terms.next_payment': 'ln_p_nextPaymen',
  'loan_terms.regular_payment': 'ln_p_regularPaymen',
  'loan_terms.additional_principal': 'ln_p_additionPrinci',
  'loan_terms.servicing_fees': 'ln_p_servicinFees',
  'loan_terms.total_payment': 'ln_p_totalPaymen',
  'loan_terms.principal': 'ln_p_principa',
  'loan_terms.unpaid_late_charges': 'ln_bl_unpaidLateCharge',
  'loan_terms.accrued_late_charges': 'ln_p_accruedLateCharge',
  'loan_terms.unpaid_interest': 'ln_bl_unpaidIntere',
  'loan_terms.accrued_interest': 'ln_p_accruedIntere',
  'loan_terms.interest_guarantee': 'ln_p_interestGuaran',
  'loan_terms.unpaid_default_interest': 'ln_bl_unpaidDefaulIntere',
  'loan_terms.accrued_default_interest': 'ln_p_accruedDefaulIntere',
  'loan_terms.charges_owed': 'ln_p_chargesOwed',
  'loan_terms.charges_interest': 'ln_p_chargesIntere',
  'loan_terms.unpaid_other': 'ln_p_unpaidOther',
  'loan_terms.amount_to_reinstate': 'ln_p_amountToReinst',
  'loan_terms.reserve_balance': 'ln_p_reserveBalanc',
  'loan_terms.escrow_balance': 'ln_p_escrowBalanc',
  'loan_terms.total_balance_due': 'ln_p_totalBalancDue',
  'loan_terms.estimated_balloon_payment': 'ln_p_estimateBallooPaymen',
  'loan_terms.default_interest': 'ln_p_defaultIntere',
  'loan_terms.other_scheduled_payments': 'ln_p_otherScheduPaymen',
  'loan_terms.to_escrow_impounds': 'ln_p_toEscrowImpoun',
  'loan_terms.accept_short_payments_enabled': 'ln_p_acceptShortPaymen',
  'loan_terms.accept_short_payments_amount': 'ln_p_acceptShortPaymenAmount',
  'loan_terms.accept_short_payments_or_percent': 'ln_p_acceptShortPaymenOr',
  'loan_terms.accept_short_payments_percent': 'ln_p_acceptShortPaymenPercen',
  'loan_terms.accept_post_maturity': 'ln_p_acceptPostma',
  'loan_terms.auto_post_enabled': 'ln_p_autopostEnable',
  'loan_terms.hold_days': 'ln_p_holdDays',
  'loan_terms.override_funds_held': 'ln_p_overrideFundsHeld',
  'loan_terms.sales_tax_enabled': 'ln_p_salesTax',
  'loan_terms.sales_tax_percent': 'ln_p_salesTaxPercent',
  'loan_terms.details_company': 'ln_p_company',
  'Terms.LoanNumber': 'ln_p_loanNumber',
  'loan_terms.assigned_csr': 'ln_p_assignedCsr',
  'loan_terms.details_originating_vendor': 'ln_p_originatVendor',
  'loan_terms.origination': 'ln_p_originat',
  'loan_terms.boarding': 'ln_p_boarding',
  'loan_terms.maturity': 'ln_pn_maturity',
  'loan_terms.maturity_date': 'ln_pn_maturityDate',
  'loan_terms.lien_position': 'ln_p_lienPositi',
  'loan_terms.loan_purpose': 'ln_p_loanPurpos',
  'loan_terms.rate_structure': 'ln_p_rateStruct',
  'loan_terms.amortization': 'ln_p_amortiza',
  'loan_terms.interest_calculation': 'ln_p_interestCalcul',
  'loan_terms.short_payments_applied_to': 'ln_p_shortPaymenApplieTo',
  'loan_terms.processing_unpaid_interest': 'ln_bl_processiUnpaidIntere',
  'loan_terms.calculation_period': 'ln_p_calculatPeriod',
  'loan_terms.seller_carry': 'ln_p_sellerCarry',
  'loan_terms.aitd_wrap': 'ln_p_aitdWrap',
  'loan_terms.rehab_construction': 'ln_p_rehabConstr',
  'loan_terms.variable_arm': 'ln_p_variableArm',
  'loan_terms.cross_collateral': 'ln_p_crossCollat',
  'loan_terms.unsecured': 'ln_p_unsecure',
  'loan_terms.limited_no_doc': 'ln_p_limitedNoDoc',
  'loan_terms.respa': 'ln_p_respa',
  'loan_terms.balloon_payment': 'ln_p_balloonPaymen',
   'loan_terms.subordination_provision': 'ln_p_subordinationProvision',
  'loan_terms.parent_account': 'ln_p_parentAccoun',
  'loan_terms.parent_account_value': 'ln_p_parentAccounValue',
  'loan_terms.child_account': 'ln_p_childAccoun',
  'loan_terms.child_account_value': 'ln_p_childAccounValue',

  // LOAN TERMS PENALTIES
  'loan_terms.prepayment_penalty': 'ln_pn_prepaymePenalt',
  'loan_terms.prepayment_penalty_expires': 'ln_pn_prepaymePenaltExpire',
  'loan_terms.prepayment_penalty_and_privilege': 'ln_pn_prepaymePenaltAndPrivil',
  'loan_terms.loan_to_value_ratio': 'ln_p_loanToValueRatio',
  'loan_terms.months': 'ln_p_months',
  'lender.funding.amount': 'ld_fd_fundingAmount',

  // ──────────────────────────────────────────────────
  // PENALTIES – map UI keys to existing DB keys
  // ──────────────────────────────────────────────────
  'loan_terms.penalties.late_charge_1.grace_period': 'ln_p_graceper',
  'loan_terms.penalties.late_charge_1.type': 'ln_p_lateChargeMethod',
  'loan_terms.penalties.late_charge_2.enabled': 'ln_p_lateNoticeEnable',
  'loan_terms.penalties.late_charge_2.grace_period': 'ln_p_graceper2',
  'loan_terms.penalties.default_interest.enabled': 'ln_p_defaultEnable',
  'loan_terms.penalties.default_interest.grace_period': 'ln_p_graceper3',
  'loan_terms.penalties.default_interest.flat_rate': 'ln_p_penFlatRate',
  'loan_terms.penalties.default_interest.distribution.lenders': 'ln_p_defaultLenderSplit',
  'loan_terms.penalties.default_interest.distribution.company': 'ln_p_defaultCost',
  'loan_terms.penalties.default_interest.distribution.origination_vendors': 'ln_p_defaultBroker',
  'loan_terms.penalties.prepayment.penalty_months': 'ln_p_penaltym',
  'loan_terms.penalties.prepayment.of_the': 'ln_p_penaltyBasedOn',
  'loan_terms.penalties.maturity.grace_period_days': 'ln_p_graceper4',

  // ──────────────────────────────────────────────────
  // PROPERTY
  // ──────────────────────────────────────────────────
  'property1.description': 'pr_p_descript',
  'property1.street': 'pr_p_street',
  'property1.city': 'pr_p_city',
  'property1.state': 'pr_p_state',
  'property1.zip': 'pr_p_zip',
  'property1.county': 'pr_p_county',
  'property1.copy_borrower_address': 'pr_p_copyBorrowAddres',
  'property1.primary_property': 'pr_p_primaryProper',
  'property1.appraisal_performed_by': 'pr_p_performeBy',
  'property1.appraisal_property_type': 'pr_p_propertyType',
  'property1.appraisal_occupancy': 'pr_p_occupanc',
  'property1.ltv': 'pr_p_ltv',
  'property1.zoning': 'pr_p_zoning',
  'property1.appraised_value': 'pr_p_appraiseValue',
  'property1.pledged_equity': 'pr_p_pledgedEquity',
  'property1.appraised_date': 'pr_p_appraiseDate',
  'property1.priority': 'pr_p_priorit',
  'property1.flood_zone': 'pr_p_floodZone',
  'property1.apn': 'pr_p_apn',
  'property1.purchase_price': 'pr_p_purchasePrice',
  'property1.down_payment': 'pr_p_downPayme',
  'property1.delinquent_taxes': 'pr_p_delinquTaxes',
  'property1.appraiser_street': 'pr_p_appraiserStreet',
  'property1.appraiser_city': 'pr_p_appraiserCity',
  'property1.appraiser_state': 'pr_p_appraiserState',
  'property1.appraiser_zip': 'pr_p_appraiserZip',
  'property1.appraiser_phone': 'pr_p_appraiserPhone',
  'property1.appraiser_email': 'pr_p_appraiserEmail',
  'property1.year_built': 'pr_p_yearBuilt',
  'property1.square_feet': 'pr_p_squareFeet',
  'property1.construction_type': 'pr_p_construcType',
  'property1.monthly_income': 'pr_p_monthlyIncome',
  'property1.annual_income': 'pr_p_annualIncome',
  'property1.lien_protective_equity': 'pr_p_lienProtecEquity',
  'property1.source_lien_info': 'pr_p_sourceLienInfo',
  'property1.thomas_map': 'pr_p_thomasMap',
  'property1.unit': 'pr_p_unit',
  'property1.delinquencies_60day': 'pr_p_delinqu60day',
  'property1.delinquencies_how_many': 'pr_p_delinquHowMany',
  'property1.currently_delinquent': 'pr_p_currentDelinqu',
  'property1.paid_by_loan': 'pr_p_paidByLoan',
  'property1.source_of_payment': 'pr_p_sourceOfPaymen',
  'property1.recording_number': 'pr_p_recordinNumber',
  'property1.primary_collateral': 'pr_p_primaryCollateral',
  'property1.purchase_date': 'pr_p_purchaseDate',
  'property1.property_generates_income': 'pr_p_propertyGeneratesIncome',
  'property1.net_monthly_income': 'pr_p_netMonthlyIncome',
  'property1.from_rent': 'pr_p_fromRent',
  'property1.from_other_describe': 'pr_p_fromOtherDescribe',
  'property1.valuation_date': 'pr_p_valuationDate',
  'property1.valuation_type': 'pr_p_valuationType',
  'property1.third_party_full_name': 'pr_p_thirdPartyFullName',
  'property1.third_party_street': 'pr_p_thirdPartyStreet',
  'property1.third_party_city': 'pr_p_thirdPartyCity',
  'property1.third_party_state': 'pr_p_thirdPartyState',
  'property1.third_party_zip': 'pr_p_thirdPartyZip',
  'property1.protective_equity': 'pr_p_protectiveEquity',
  'property1.cltv': 'pr_p_cltv',
  'property1.info_provided_by': 'pr_p_infoProvidedBy',

  // PROPERTY LEGAL
  'property1.legal_description': 'pr_lg_legalDescri',
  'property1.lot': 'pr_lg_lot',
  'property1.block': 'pr_p_block',
  'property1.tract': 'pr_lg_tract',

  // PROPERTY INSURANCE
  'property1.insurance_description': 'pr_p_descript2',
  'property1.insured_s_name': 'pr_p_insuredName',
  'property1.insurance_company_name': 'pr_p_companyName',
  'property1.insurance_policy_number': 'pr_ins_insurancPolicyNumber',
  'property1.insurance_expiration': 'pr_p_expirati',
  'property1.insurance_coverage': 'pr_p_coverage',
  'property1.insurance_active': 'pr_p_active',
  'property1.agent_s_name': 'pr_p_agentsName',
  'property1.insurance_business_address': 'pr_p_businessAddres',
  'property1.insurance_phone_number': 'pr_p_insurancPhoneNumber',
  'property1.insurance_fax_number': 'pr_p_faxNumber',
  'property1.insurance_e_mail': 'pr_p_email',
  'property1.insurance_annual_premium': 'pr_ins_annualPremium',
  'property1.insurance_frequency': 'pr_ins_frequency',
  'property1.insurance_impounds_active': 'pr_ins_impoundsActive',
  'property1.insurance_attempt_agent': 'pr_ins_attemptAgent',
  'property1.insurance_attempt_borrower': 'pr_ins_attemptBorrower',
  'property1.insurance_lender_notified': 'pr_ins_lenderNotified',

  // PROPERTY LIENS
  'property1.lien_property': 'pr_li_lienProper',
  'property1.lien_priority': 'pr_li_lienPriori',
  'property1.lien_holder': 'pr_li_lienHolder',
  'property1.lien_account': 'pr_li_lienAccoun',
  'property1.lien_contact': 'pr_li_lienContac',
  'property1.lien_phone': 'pr_li_lienPhone',
  'property1.lien_original_balance': 'pr_li_lienOriginBalanc',
  'property1.lien_current_balance': 'pr_li_lienCurrenBalanc',
  'property1.lien_regular_payment': 'pr_li_lienRegulaPaymen',
  'property1.lien_last_checked': 'pr_li_lienLastChecke',

  // LIEN TAB (lien.* dot-notation from LienSectionContent)
  'lien.property': 'pr_li_lienProper',
  'lien.priority': 'pr_li_lienPriori',
  'lien.holder': 'pr_li_lienHolder',
  'lien.account': 'pr_li_lienAccoun2',
  'lien.contact': 'pr_li_lienContac',
  'lien.phone': 'pr_li_lienPhone',
  'lien.fax': 'li_gd_fax',
  'lien.email': 'li_gd_email',
  'lien.loan_type': 'li_lt_loanType',
  'lien.anticipated': 'li_lt_anticipated',
  'lien.existing_remain': 'li_lt_existingRemain',
  'lien.existing_paydown': 'li_lt_existingPaydown',
  'lien.existing_payoff': 'li_lt_existingPayoff',
  'lien.existing_paydown_amount': 'li_lt_existingPaydownAmount',
  'lien.existing_payoff_amount': 'li_lt_existingPayoffAmount',
  'lien.lien_priority_now': 'pr_li_lienPrioriNow',
  'lien.lien_priority_after': 'pr_li_lienPrioriAfter',
  'lien.original_balance': 'pr_li_lienOriginBalanc2',
  'lien.current_balance': 'pr_li_lienCurrenBalanc2',
  'lien.balance_after': 'li_bp_balanceAfter',
  'lien.regular_payment': 'pr_li_lienRegulaPaymen2',
  'lien.recording_number': 'li_rt_recordingNumber',
  'lien.recording_number_flag': 'li_rt_recordingNumberFlag',
  'lien.recording_date': 'li_rt_recordingDate',
  'lien.last_checked': 'pr_li_lienLastChecke',
  'lien.last_verified': 'pr_li_lienLastChecke2',
  'lien.senior_lien_tracking': 'pr_li_seniorLienTracki',
  'lien.note': 'pr_li_lienHolder2',
  'lien.this_loan': 'li_gd_thisLoan',
  'lien.estimate': 'li_gd_estimate',
  'lien.status': 'pr_li_lienHolder3',
  'lien.interest_rate': 'li_gd_interestRate',
  'lien.maturity_date': 'li_gd_maturityDate',
  'lien.delinquencies_60day': 'pr_li_delinqu60day',
  'lien.delinquencies_how_many': 'pr_li_delinquHowMany',
  'lien.currently_delinquent': 'pr_li_currentDelinqu',
  'lien.paid_by_loan': 'pr_li_paidByLoan',
  'lien.source_of_payment': 'pr_li_sourceOfPayment',
  'lien.loan_type_dropdown': 'li_lt_loanTypeDropdown',
  'lien.anticipated_amount': 'li_lt_anticipatedAmount',
  'lien.remaining_new_lien_priority': 'li_gd_remainingNewLienPriority',
  'lien.new_remaining_balance': 'li_gd_newRemainingBalance',
  'lien.balloon': 'li_gd_balloon',
  'lien.balloon_amount': 'li_gd_balloonAmount',
  'lien.slt_active': 'li_slt_active',
  'lien.slt_current': 'li_slt_current',
  'lien.slt_delinquent': 'li_slt_delinquent',
  'lien.slt_delinquent_days': 'li_slt_delinquentDays',
  'lien.slt_under_modification': 'li_slt_underModification',
  'lien.slt_foreclosure': 'li_slt_foreclosure',
  'lien.slt_foreclosure_date': 'li_slt_foreclosureDate',
  'lien.slt_paid_off': 'li_slt_paidOff',
  'lien.slt_last_payment_made': 'li_slt_lastPaymentMade',
  'lien.slt_next_payment_due': 'li_slt_nextPaymentDue',
  'lien.slt_current_balance': 'li_slt_currentBalance',
  'lien.slt_request_submitted': 'li_slt_requestSubmitted',
  'lien.slt_response_received': 'li_slt_responseReceived',
  'lien.slt_unable_to_verify': 'li_slt_unableToVerify',
  'lien.slt_lender_notified': 'li_slt_lenderNotified',
  'lien.slt_lender_notified_date': 'li_slt_lenderNotifiedDate',
  'lien.currently_delinquent_amount': 'li_gd_currentlyDelinquentAmount',
  'lien.source_of_information': 'lien1.source_of_information',

  // PROPERTY TAX
  'property1.tax.payee': 'pr_p_taxPayee',
  'property1.tax.payee_address': 'pr_p_taxPayeeAddres',
  'property1.tax.next_due_date': 'pr_p_taxNextDueDate',
  'property1.tax.frequency': 'pr_p_taxFreque',
  'property1.tax.hold': 'pr_p_taxHold',
  'property1.tax.ref': 'pr_p_taxRef',
  'property1.tax.memo': 'pr_p_taxMemo',
  'property1.tax.type': 'pr_p_taxType',
  'property1.tax.authority': 'pr_p_authorit',
  'property1.tax.tax_tracking': 'pr_p_taxTracki',
  'property1.tax.last_verified': 'pr_p_lastVerifi',
  'property1.tax.tracking_status': 'pr_p_taxTrackiStatus',

  // ──────────────────────────────────────────────────
  // BROKER
  // ──────────────────────────────────────────────────
  'broker.id': 'bk_p_brokerId',
  'broker.License': 'bk_p_brokerLicens',
  'broker.company': 'bk_p_company',
  'broker.first_name': 'bk_p_firstName',
  'broker.middle_name': 'bk_p_middleName',
  'broker.last_name': 'bk_p_lastName',
  'broker.email': 'bk_p_email',
  'broker.address.street': 'bk_p_street',
  'broker.address.city': 'bk_p_city',
  'broker.address.state': 'bk_p_state',
  'broker.address.zip': 'bk_p_zip',
  'broker.tax_id_type': 'bk_p_taxIdType',
  'broker.tax_id': 'bk_p_taxId',
  'broker.issue_1099': 'bk_p_issue1099',
  'broker.phone.home': 'bk_p_homePhone',
  'broker.phone.work': 'bk_p_workPhone',
  'broker.phone.cell': 'bk_p_cellPhone',
  'broker.phone.fax': 'bk_p_fax',
  'broker.preferred.home': 'bk_p_preferreHomePhone',
  'broker.preferred.work': 'bk_p_preferreWorkPhone',
  'broker.preferred.cell': 'bk_p_preferreCellPhone',
  'broker.preferred.fax': 'bk_p_preferreFax',
  'broker.send_pref.payment_notification': 'bk_p_paymentNotifi',
  'broker.send_pref.late_notice': 'bk_p_lateNotice',
  'broker.send_pref.lender_statement': 'bk_p_lenderStatem',
  'broker.send_pref.borrower_statement': 'bk_p_borrowerStatem',
  'broker.send_pref.maturity_notice': 'bk_p_maturityNotice',

  // BROKER BANKING
  'broker.banking.ach_status': 'bk_p_achStatus',
  'broker.banking.bank': 'bk_p_bank',
  'broker.banking.routing_number': 'bk_b_routingNumber',
  'broker.banking.account_number': 'bk_p_accountNumber',
  'broker.banking.account_type': 'bk_p_accountType',
  'broker.banking.account_name': 'bk_p_accountName',
  'broker.banking.account_id': 'bk_p_accountId',
  'broker.banking.further_credit_to': 'bk_p_furtherCreditTo',
  'broker.banking.by_check': 'bk_p_byCheck',
  'broker.banking.check_same_as_mailing': 'bk_p_sameAsMailin',
  'broker.banking.check_address': 'bk_p_checkAddres',
  'broker.banking.check_city': 'bk_p_checkCity',
  'broker.banking.check_zip': 'bk_p_checkZip',
  'broker.banking.ach_email': 'bk_p_achEmail',
  'broker.banking.cc_name': 'bk_p_creditCardName',
  'broker.banking.cc_number': 'bk_p_cardNumber',
  'broker.banking.cc_security_code': 'bk_p_securityCode',
  'broker.banking.cc_expiration': 'bk_p_expirati',
  'broker.banking.cc_zip': 'bk_p_creditCardZip',

  // ──────────────────────────────────────────────────
  // CHARGES
  // ──────────────────────────────────────────────────
  'charge.description': 'ch_p_descript',
  'charge.unpaid_balance': 'ch_p_unpaidBalanc',
  'charge.owed_to': 'ch_p_owedToAccoun',
  'charge.owed_from': 'ch_p_owedFrom',
  'charge.total_due': 'ch_p_totalDue',
  'charge.interest_from': 'ch_p_interestFrom',
  'charge.date_of_charge': 'ch_p_dateOfCharge',
  'charge.interest_rate': 'ch_p_interestRate',
  'charge.notes': 'ch_p_notes',
  'charge.reference': 'ch_p_referenc',
  'charge.charge_type': 'ch_p_chargeType',
  'charge.deferred': 'ch_p_deferred',
  'charge.original_amount': 'ch_p_originalAmount',
  'charge.account': 'ch_p_account',
  'charge.borrower_full_name': 'ch_p_borrowerFullName',
  'charge.advanced_by_account': 'ch_p_advancedByAccoun',
  'charge.advanced_by_lender_name': 'ch_p_advancedByLenderName',
  'charge.advanced_by_amount': 'ch_p_advancedByAmount',
  'charge.on_behalf_of_account': 'ch_p_onBehalfOfAccoun',
  'charge.on_behalf_of_lender_name': 'ch_p_onBehalfOfLender',
  'charge.on_behalf_of_amount': 'ch_p_onBehalfOfAmount',
  'charge.amount_owed_by_borrower': 'ch_p_amountOwedByBorrow',
  'charge.accrued_interest': 'ch_p_accruedIntere',
  'charge.distribute_between_all_lenders': 'ch_p_distribuBetweenAll',
  'charge.department': 'ch_p_department',
  'charge.category': 'ch_p_category',
  'charge.details': 'ch_p_details',
  'charge.current_balance': 'ch_p_currentBalance',
  'charge.balance_due_as_of': 'ch_p_balanceDueAsOf',
  'charge.balance_due': 'ch_p_balanceDue',
  'charge.advanced_by_deferred': 'ch_p_advancedByDeferred',
  'charge.advanced_by_total': 'ch_p_advancedByTotal',
  'charge.on_behalf_of_billing': 'ch_p_onBehalfOfBilling',
  'charge.on_behalf_of_total': 'ch_p_onBehalfOfTotal',

  // Also map the charge_ dictionary keys used in CHARGE_UI_TO_DICT
  'charges.description': 'ch_p_descript',
  'charges.unpaid_balance': 'ch_p_unpaidBalanc',
  'charges.owed_to': 'ch_p_owedToAccoun',
  'charges.total_due': 'ch_p_totalDue',
  'charges.interest_from': 'ch_p_interestFrom',
  'charges.date_of_charge': 'ch_p_dateOfCharge',
  'charges.interest_rate': 'ch_p_interestRate',
  'charges.notes': 'ch_p_notes',
  'charges.reference': 'ch_p_referenc',
  'charges.charge_type': 'ch_p_chargeType',
  'charges.deferred': 'ch_p_deferred',
  'charges.original_amount': 'ch_p_originalAmount',
  'charges.account': 'ch_p_account',
  'charges.borrower_full_name': 'ch_p_borrowerFullName',
  'charges.advanced_by_account': 'ch_p_advancedByAccoun',
  'charges.advanced_by_lender_name': 'ch_p_advancedByLenderName',
  'charges.advanced_by_amount': 'ch_p_advancedByAmount',
  'charges.on_behalf_of_account': 'ch_p_onBehalfOfAccoun',
  'charges.on_behalf_of_lender_name': 'ch_p_onBehalfOfLender',
  'charges.on_behalf_of_amount': 'ch_p_onBehalfOfAmount',
  'charges.amount_owed_by_borrower': 'ch_p_amountOwedByBorrow',
  'charges.accrued_interest': 'ch_p_accruedIntere',
  'charges.owed_from': 'ch_p_owedFrom',
  'charges.distribute_between_all_lenders': 'ch_p_distribuBetweenAll',
  'charges.department': 'ch_p_department',
  'charges.category': 'ch_p_category',
  'charges.details': 'ch_p_details',
  'charges.current_balance': 'ch_p_currentBalance',
  'charges.balance_due_as_of': 'ch_p_balanceDueAsOf',
  'charges.balance_due': 'ch_p_balanceDue',
  'charges.advanced_by_deferred': 'ch_p_advancedByDeferred',
  'charges.advanced_by_total': 'ch_p_advancedByTotal',
  'charges.on_behalf_of_billing': 'ch_p_onBehalfOfBilling',
  'charges.on_behalf_of_total': 'ch_p_onBehalfOfTotal',

  // Charge dictionary format keys (used by CHARGE_UI_TO_DICT reverse mapping)
  'charge_date': 'ch_p_dateOfCharge',
  'charge_description': 'ch_p_descript',
  'charge_interest_rate': 'ch_p_interestRate',
  'charge_interest_start_date': 'ch_p_interestFrom',
  'charge_reference': 'ch_p_referenc',
  'charge_type': 'ch_p_chargeType',
  'charge_notes': 'ch_p_notes',
  'charge_original_amount': 'ch_p_originalAmount',
  'charge_is_deferred': 'ch_p_deferred',
  'charge_accrued_interest': 'ch_p_accruedIntere',
  'charge_unpaid_balance': 'ch_p_unpaidBalanc',
  'charge_total_due': 'ch_p_totalDue',
  'charge_owed_to': 'ch_p_owedToAccoun',
  'charge_owed_from': 'ch_p_owedFrom',
  'charge_account': 'ch_p_account',
  'charge_borrower_full_name': 'ch_p_borrowerFullName',
  'charge_distribute_between_all_lenders': 'ch_p_distribuBetweenAll',
  'charge_department': 'ch_p_department',
  'charge_category': 'ch_p_category',
  'charge_details': 'ch_p_details',
  'charge_current_balance': 'ch_p_currentBalance',
  'charge_balance_due_as_of': 'ch_p_balanceDueAsOf',
  'charge_balance_due': 'ch_p_balanceDue',
  'charge_advanced_by_account': 'ch_p_advancedByAccoun',
  'charge_advanced_by_lender_name': 'ch_p_advancedByLenderName',
  'charge_advanced_by_amount': 'ch_p_advancedByAmount',
  'charge_advanced_by_deferred': 'ch_p_advancedByDeferred',
  'charge_advanced_by_total': 'ch_p_advancedByTotal',
  'charge_on_behalf_of_account': 'ch_p_onBehalfOfAccoun',
  'charge_on_behalf_of_lender_name': 'ch_p_onBehalfOfLender',
  'charge_on_behalf_of_amount': 'ch_p_onBehalfOfAmount',
  'charge_on_behalf_of_billing': 'ch_p_onBehalfOfBilling',
  'charge_on_behalf_of_total': 'ch_p_onBehalfOfTotal',
  'charge_amount_owed_by_borrower': 'ch_p_amountOwedByBorrow',

  // ──────────────────────────────────────────────────
  // ORIGINATION FEES (HUD-1 Form)
  // ──────────────────────────────────────────────────

  // 800 Custom Item (9 fields)
  'origination_fees.800_custom_item_label': 'of_fe_800CustomItemLabel',
  'origination_fees.800_custom_item_payable_to': 'of_fe_800CustomItemPayabl',
  'origination_fees.800_custom_item_d': 'of_fe_800CustomItemD',
  'origination_fees.800_custom_item_charge': 'of_fe_800CustomItemCharge',
  'origination_fees.800_custom_item_broker': 'of_fe_800CustomItemBroker',
  'origination_fees.800_custom_item_others': 'of_fe_800CustomItemOthers',
  'origination_fees.800_custom_item_apr': 'of_fe_800CustomItemApr',
  'origination_fees.800_custom_item_paid_to_company': 'of_fe_800CustomItemPaid',
  'origination_fees.800_custom_item_oral_disclosure': 'of_fe_800CustomItemOral',

  // 801 Lenders Loan Origination Fee (8 fields)
  'origination_fees.801_lenders_loan_origination_fee_payable_to': 'of_fe_801LenderLoanOrigin5',
  'origination_fees.801_lenders_loan_origination_fee_d': 'of_fe_lendersLoanOriginFee',
  'origination_fees.801_lenders_loan_origination_fee_charge': 'of_fe_801LenderLoanOrigin2',
  'origination_fees.801_lenders_loan_origination_fee_broker': 'of_801_lenderLoanOriginationFee_broker',
  'origination_fees.801_lenders_loan_origination_fee_others': 'of_801_lenderLoanOriginationFee_others',
  'origination_fees.801_lenders_loan_origination_fee_apr': 'of_fe_801LenderLoanOrigin',
  'origination_fees.801_lenders_loan_origination_fee_paid_to_company': 'of_fe_801LenderLoanOrigin4',
  'origination_fees.801_lenders_loan_origination_fee_oral_disclosure': 'of_fe_801LenderLoanOrigin3',

  // 802 Lenders Loan Discount Fee (8 fields)
  'origination_fees.802_lenders_loan_discount_fee_payable_to': 'of_fe_802LenderLoanDiscou5',
  'origination_fees.802_lenders_loan_discount_fee_d': 'of_fe_lendersLoanDiscouFee',
  'origination_fees.802_lenders_loan_discount_fee_charge': 'of_fe_802LenderLoanDiscou2',
  'origination_fees.802_lenders_loan_discount_fee_broker': 'of_802_lenderLoanDiscountFee_broker',
  'origination_fees.802_lenders_loan_discount_fee_others': 'of_802_lenderLoanDiscountFee_others',
  'origination_fees.802_lenders_loan_discount_fee_apr': 'of_fe_802LenderLoanDiscou',
  'origination_fees.802_lenders_loan_discount_fee_paid_to_company': 'of_fe_802LenderLoanDiscou4',
  'origination_fees.802_lenders_loan_discount_fee_oral_disclosure': 'of_fe_802LenderLoanDiscou3',

  // 803 Appraisal Fee (8 fields)
  'origination_fees.803_appraisal_fee_payable_to': 'of_fe_803AppraiFeePayabl',
  'origination_fees.803_appraisal_fee_d': 'of_fe_appraisaFeeD',
  'origination_fees.803_appraisal_fee_charge': 'of_fe_803AppraiFeeCharge',
  'origination_fees.803_appraisal_fee_broker': 'of_803_appraisalFee_broker',
  'origination_fees.803_appraisal_fee_others': 'of_803_appraisalFee_others',
  'origination_fees.803_appraisal_fee_apr': 'of_fe_803AppraiFeeApr',
  'origination_fees.803_appraisal_fee_paid_to_company': 'of_fe_803AppraiFeePaid',
  'origination_fees.803_appraisal_fee_oral_disclosure': 'of_fe_803AppraiFeeOral',

  // 804 Credit Report (8 fields)
  'origination_fees.804_credit_report_payable_to': 'of_fe_804CreditReportPayabl',
  'origination_fees.804_credit_report_d': 'of_fe_creditReportD',
  'origination_fees.804_credit_report_charge': 'of_fe_804CreditReportCharge',
  'origination_fees.804_credit_report_broker': 'of_804_creditReportFee_broker',
  'origination_fees.804_credit_report_others': 'of_804_creditReportFee_others',
  'origination_fees.804_credit_report_apr': 'of_fe_804CreditReportApr',
  'origination_fees.804_credit_report_paid_to_company': 'of_fe_804CreditReportPaid',
  'origination_fees.804_credit_report_oral_disclosure': 'of_fe_804CreditReportOral',

  // 805 Lenders Inspection Fee (8 fields)
  'origination_fees.805_lenders_inspection_fee_payable_to': 'of_fe_805LenderInspecFee5',
  'origination_fees.805_lenders_inspection_fee_d': 'of_fe_lendersInspecFeeD',
  'origination_fees.805_lenders_inspection_fee_charge': 'of_fe_805LenderInspecFee2',
  'origination_fees.805_lenders_inspection_fee_broker': 'of_805_lenderInspectionFee_broker',
  'origination_fees.805_lenders_inspection_fee_others': 'of_805_lenderInspectionFee_others',
  'origination_fees.805_lenders_inspection_fee_apr': 'of_fe_805LenderInspecFee',
  'origination_fees.805_lenders_inspection_fee_paid_to_company': 'of_fe_805LenderInspecFee4',
  'origination_fees.805_lenders_inspection_fee_oral_disclosure': 'of_fe_805LenderInspecFee3',

  // 808 Mortgage Broker Fee (8 fields)
  'origination_fees.808_mortgage_broker_fee_payable_to': 'of_fe_808MortgaBrokerFee5',
  'origination_fees.808_mortgage_broker_fee_d': 'of_fe_mortgageBrokerFeeD',
  'origination_fees.808_mortgage_broker_fee_charge': 'of_fe_808MortgaBrokerFee2',
  'origination_fees.808_mortgage_broker_fee_broker': 'of_808_mortgageBrokerCommissionFee_broker',
  'origination_fees.808_mortgage_broker_fee_others': 'of_808_mortgageBrokerCommissionFee_others',
  'origination_fees.808_mortgage_broker_fee_apr': 'of_fe_808MortgaBrokerFee',
  'origination_fees.808_mortgage_broker_fee_paid_to_company': 'of_fe_808MortgaBrokerFee4',
  'origination_fees.808_mortgage_broker_fee_oral_disclosure': 'of_fe_808MortgaBrokerFee3',

  // 809 Tax Service Fee (8 fields)
  'origination_fees.809_tax_service_fee_payable_to': 'of_fe_809TaxServicFee5',
  'origination_fees.809_tax_service_fee_d': 'of_fe_taxServicFeeD',
  'origination_fees.809_tax_service_fee_charge': 'of_fe_809TaxServicFee2',
  'origination_fees.809_tax_service_fee_broker': 'of_809_taxServiceFee_broker',
  'origination_fees.809_tax_service_fee_others': 'of_809_taxServiceFee_others',
  'origination_fees.809_tax_service_fee_apr': 'of_fe_809TaxServicFee',
  'origination_fees.809_tax_service_fee_paid_to_company': 'of_fe_809TaxServicFee4',
  'origination_fees.809_tax_service_fee_oral_disclosure': 'of_fe_809TaxServicFee3',

  // 810 Processing Fee (8 fields)
  'origination_fees.810_processing_fee_payable_to': 'of_fe_810ProcesFeePayabl',
  'origination_fees.810_processing_fee_d': 'of_fe_processiFeeD',
  'origination_fees.810_processing_fee_charge': 'of_fe_810ProcesFeeCharge',
  'origination_fees.810_processing_fee_broker': 'of_810_processingFee_broker',
  'origination_fees.810_processing_fee_others': 'of_810_processingFee_others',
  'origination_fees.810_processing_fee_apr': 'of_fe_810ProcesFeeApr',
  'origination_fees.810_processing_fee_paid_to_company': 'of_fe_810ProcesFeePaid',
  'origination_fees.810_processing_fee_oral_disclosure': 'of_fe_810ProcesFeeOral',

  // 811 Underwriting Fee (8 fields)
  'origination_fees.811_underwriting_fee_payable_to': 'of_fe_811UnderwFeePayabl',
  'origination_fees.811_underwriting_fee_d': 'of_fe_underwriFeeD',
  'origination_fees.811_underwriting_fee_charge': 'of_fe_811UnderwFeeCharge',
  'origination_fees.811_underwriting_fee_broker': 'of_811_underwritingFee_broker',
  'origination_fees.811_underwriting_fee_others': 'of_811_underwritingFee_others',
  'origination_fees.811_underwriting_fee_apr': 'of_fe_811UnderwFeeApr',
  'origination_fees.811_underwriting_fee_paid_to_company': 'of_fe_811UnderwFeePaid',
  'origination_fees.811_underwriting_fee_oral_disclosure': 'of_fe_811UnderwFeeOral',

  // 812 Wire Transfer Fee (8 fields)
  'origination_fees.812_wire_transfer_fee_payable_to': 'of_fe_812WireTransfFee5',
  'origination_fees.812_wire_transfer_fee_d': 'of_fe_wireTransfFeeD',
  'origination_fees.812_wire_transfer_fee_charge': 'of_fe_812WireTransfFee2',
  'origination_fees.812_wire_transfer_fee_broker': 'of_812_wireTransferFee_broker',
  'origination_fees.812_wire_transfer_fee_others': 'of_812_wireTransferFee_others',
  'origination_fees.812_wire_transfer_fee_apr': 'of_fe_812WireTransfFee',
  'origination_fees.812_wire_transfer_fee_paid_to_company': 'of_fe_812WireTransfFee4',
  'origination_fees.812_wire_transfer_fee_oral_disclosure': 'of_fe_812WireTransfFee3',

  // 900 Custom Item (9 fields)
  'origination_fees.900_custom_item_label': 'of_fe_900CustomItemLabel',
  'origination_fees.900_custom_item_payable_to': 'of_fe_900CustomItemPayabl',
  'origination_fees.900_custom_item_d': 'of_fe_900CustomItemD',
  'origination_fees.900_custom_item_charge': 'of_fe_900CustomItemCharge',
  'origination_fees.900_custom_item_broker': 'of_fe_900CustomItemBroker',
  'origination_fees.900_custom_item_others': 'of_fe_900CustomItemOthers',
  'origination_fees.900_custom_item_apr': 'of_fe_900CustomItemApr',
  'origination_fees.900_custom_item_paid_to_company': 'of_fe_900CustomItemPaid',
  'origination_fees.900_custom_item_oral_disclosure': 'of_fe_900CustomItemOral',

  // 901 Interest For Days (8 fields)
  'origination_fees.901_interest_for_days_payable_to': 'of_fe_901IntereForDays5',
  'origination_fees.901_interest_for_days_d': 'of_fe_interestForDaysD',
  'origination_fees.901_interest_for_days_charge': 'of_fe_901IntereForDays2',
  'origination_fees.901_interest_for_days_broker': 'of_901_int_b',
  'origination_fees.901_interest_for_days_others': 'of_901_int_o',
  'origination_fees.901_interest_for_days_apr': 'of_fe_901IntereForDays',
  'origination_fees.901_interest_for_days_paid_to_company': 'of_fe_901IntereForDays4',
  'origination_fees.901_interest_for_days_oral_disclosure': 'of_fe_901IntereForDays3',

  // 901 dynamic description fields (days count + per day amount)
  'origination_fees.901_interest_for_days_days': 'of_int_days',
  'origination_fees.901_interest_for_days_per_day': 'of_int_pd',

  // 902 Mortgage Insurance Premiums (8 fields)
  'origination_fees.902_mortgage_insurance_premiums_payable_to': 'of_fe_902MortgaInsuraPremiu5',
  'origination_fees.902_mortgage_insurance_premiums_d': 'of_fe_mortgageInsuraPremiuD',
  'origination_fees.902_mortgage_insurance_premiums_charge': 'of_fe_902MortgaInsuraPremiu2',
  'origination_fees.902_mortgage_insurance_premiums_broker': 'of_902_mi_b',
  'origination_fees.902_mortgage_insurance_premiums_others': 'of_902_mi_o',
  'origination_fees.902_mortgage_insurance_premiums_apr': 'of_fe_902MortgaInsuraPremiu',
  'origination_fees.902_mortgage_insurance_premiums_paid_to_company': 'of_fe_902MortgaInsuraPremiu4',
  'origination_fees.902_mortgage_insurance_premiums_oral_disclosure': 'of_fe_902MortgaInsuraPremiu3',

  // 903 Hazard Insurance Premiums (8 fields)
  'origination_fees.903_hazard_insurance_premiums_payable_to': 'of_fe_903HazardInsuraPremiu5',
  'origination_fees.903_hazard_insurance_premiums_d': 'of_fe_hazardInsuraPremiuD',
  'origination_fees.903_hazard_insurance_premiums_charge': 'of_fe_903HazardInsuraPremiu2',
  'origination_fees.903_hazard_insurance_premiums_broker': 'of_903_hi_b',
  'origination_fees.903_hazard_insurance_premiums_others': 'of_903_hi_o',
  'origination_fees.903_hazard_insurance_premiums_apr': 'of_fe_903HazardInsuraPremiu',
  'origination_fees.903_hazard_insurance_premiums_paid_to_company': 'of_fe_903HazardInsuraPremiu4',
  'origination_fees.903_hazard_insurance_premiums_oral_disclosure': 'of_fe_903HazardInsuraPremiu3',

  // 904 County Property Taxes (8 fields)
  'origination_fees.904_county_property_taxes_payable_to': 'of_fe_904CountyProperTaxes5',
  'origination_fees.904_county_property_taxes_d': 'of_fe_countyProperTaxesD',
  'origination_fees.904_county_property_taxes_charge': 'of_fe_904CountyProperTaxes2',
  'origination_fees.904_county_property_taxes_broker': 'of_904_tax_b',
  'origination_fees.904_county_property_taxes_others': 'of_904_tax_o',
  'origination_fees.904_county_property_taxes_apr': 'of_fe_904CountyProperTaxes',
  'origination_fees.904_county_property_taxes_paid_to_company': 'of_fe_904CountyProperTaxes4',
  'origination_fees.904_county_property_taxes_oral_disclosure': 'of_fe_904CountyProperTaxes3',

  // 905 VA Funding Fee (8 fields)
  'origination_fees.905_va_funding_fee_payable_to': 'of_fe_905VaFundinFee5',
  'origination_fees.905_va_funding_fee_d': 'of_fe_vaFundinFeeD',
  'origination_fees.905_va_funding_fee_charge': 'of_fe_905VaFundinFee2',
  'origination_fees.905_va_funding_fee_broker': 'of_905_va_b',
  'origination_fees.905_va_funding_fee_others': 'of_905_va_o',
  'origination_fees.905_va_funding_fee_apr': 'of_fe_905VaFundinFee',
  'origination_fees.905_va_funding_fee_paid_to_company': 'of_fe_905VaFundinFee4',
  'origination_fees.905_va_funding_fee_oral_disclosure': 'of_fe_905VaFundinFee3',

  // 1000 Custom Item (9 fields)
  'origination_fees.1000_custom_item_label': 'of_fe_1000CustomItemLabel',
  'origination_fees.1000_custom_item_payable_to': 'of_fe_1000CustomItemPayabl',
  'origination_fees.1000_custom_item_d': 'of_fe_1000CustomItemD',
  'origination_fees.1000_custom_item_charge': 'of_fe_1000CustomItemCharge',
  'origination_fees.1000_custom_item_broker': 'of_fe_1000CustomItemBroker',
  'origination_fees.1000_custom_item_others': 'of_fe_1000CustomItemOthers',
  'origination_fees.1000_custom_item_apr': 'of_fe_1000CustomItemApr',
  'origination_fees.1000_custom_item_paid_to_company': 'of_fe_1000CustomItemPaid',
  'origination_fees.1000_custom_item_oral_disclosure': 'of_fe_1000CustomItemOral',

  // 1001 Hazard Insurance Reserves (months/perMonth/total + HUD fields)
  'origination_fees.1001_hazard_insurance_months': 'of_fe_hazardInsuraMonths',
  'origination_fees.1001_hazard_insurance_per_month': 'of_fe_hazardInsuraPerMonth',
  'origination_fees.1001_hazard_insurance_total': 'of_fe_hazardInsuraTotal',
  'origination_fees.1001_hazard_insurance_charge': 'of_fe_1001HazardInsuraCharge',
  'origination_fees.1001_hazard_insurance_broker': 'of_1001_hi_b',
  'origination_fees.1001_hazard_insurance_others': 'of_1001_hi_o',
  'origination_fees.1001_hazard_insurance_apr': 'of_fe_1001HazardInsuraApr',
  'origination_fees.1001_hazard_insurance_paid_to_company': 'of_fe_1001HazardInsuraPaid',
  'origination_fees.1001_hazard_insurance_oral_disclosure': 'of_fe_1001HazardInsuraOral',

  // 1002 Mortgage Insurance Reserves
  'origination_fees.1002_mortgage_insurance_months': 'of_fe_mortgageInsuraMonths',
  'origination_fees.1002_mortgage_insurance_per_month': 'of_fe_mortgageInsuraPerMonth',
  'origination_fees.1002_mortgage_insurance_total': 'of_fe_mortgageInsuraTotal',
  'origination_fees.1002_mortgage_insurance_charge': 'of_fe_1002MortgaInsuraCharge',
  'origination_fees.1002_mortgage_insurance_broker': 'of_1002_mi_b',
  'origination_fees.1002_mortgage_insurance_others': 'of_1002_mi_o',
  'origination_fees.1002_mortgage_insurance_apr': 'of_fe_1002MortgaInsuraApr',
  'origination_fees.1002_mortgage_insurance_paid_to_company': 'of_fe_1002MortgaInsuraPaid',
  'origination_fees.1002_mortgage_insurance_oral_disclosure': 'of_fe_1002MortgaInsuraOral',

  // 1004 Co Property Taxes Reserves
  'origination_fees.1004_co_property_taxes_months': 'of_fe_coProperTaxesMonths',
  'origination_fees.1004_co_property_taxes_per_month': 'of_fe_coProperTaxesPer',
  'origination_fees.1004_co_property_taxes_total': 'of_fe_coProperTaxesTotal',
  'origination_fees.1004_co_property_taxes_charge': 'of_fe_1004CoProperTaxes2',
  'origination_fees.1004_co_property_taxes_broker': 'of_1004_tax_b',
  'origination_fees.1004_co_property_taxes_others': 'of_1004_tax_o',
  'origination_fees.1004_co_property_taxes_apr': 'of_fe_1004CoProperTaxes',
  'origination_fees.1004_co_property_taxes_paid_to_company': 'of_fe_1004CoProperTaxes4',
  'origination_fees.1004_co_property_taxes_oral_disclosure': 'of_fe_1004CoProperTaxes3',

  // 1100 Custom Item (9 fields)
  'origination_fees.1100_custom_item_label': 'of_fe_1100CustomItemLabel',
  'origination_fees.1100_custom_item_payable_to': 'of_fe_1100CustomItemPayabl',
  'origination_fees.1100_custom_item_d': 'of_fe_1100CustomItemD',
  'origination_fees.1100_custom_item_charge': 'of_fe_1100CustomItemCharge',
  'origination_fees.1100_custom_item_broker': 'of_fe_1100CustomItemBroker',
  'origination_fees.1100_custom_item_others': 'of_fe_1100CustomItemOthers',
  'origination_fees.1100_custom_item_apr': 'of_fe_1100CustomItemApr',
  'origination_fees.1100_custom_item_paid_to_company': 'of_fe_1100CustomItemPaid',
  'origination_fees.1100_custom_item_oral_disclosure': 'of_fe_1100CustomItemOral',

  // 1101 Settlement Closing Fee (8 fields)
  'origination_fees.1101_settlement_closing_fee_payable_to': 'of_fe_1101SettleClosinFee5',
  'origination_fees.1101_settlement_closing_fee_d': 'of_fe_settlemeFeeD',
  'origination_fees.1101_settlement_closing_fee_charge': 'of_fe_1101SettleClosinFee2',
  'origination_fees.1101_settlement_closing_fee_broker': 'of_1101_set_b',
  'origination_fees.1101_settlement_closing_fee_others': 'of_1101_set_o',
  'origination_fees.1101_settlement_closing_fee_apr': 'of_fe_1101SettleClosinFee',
  'origination_fees.1101_settlement_closing_fee_paid_to_company': 'of_fe_1101SettleClosinFee4',
  'origination_fees.1101_settlement_closing_fee_oral_disclosure': 'of_fe_1101SettleClosinFee3',

  // 1105 Doc Preparation Fee (8 fields)
  'origination_fees.1105_doc_preparation_fee_payable_to': 'of_fe_1105DocPreparFee5',
  'origination_fees.1105_doc_preparation_fee_d': 'of_fe_docPreparFeeD',
  'origination_fees.1105_doc_preparation_fee_charge': 'of_fe_1105DocPreparFee2',
  'origination_fees.1105_doc_preparation_fee_broker': 'of_1105_doc_b',
  'origination_fees.1105_doc_preparation_fee_others': 'of_1105_doc_o',
  'origination_fees.1105_doc_preparation_fee_apr': 'of_fe_1105DocPreparFee',
  'origination_fees.1105_doc_preparation_fee_paid_to_company': 'of_fe_1105DocPreparFee4',
  'origination_fees.1105_doc_preparation_fee_oral_disclosure': 'of_fe_1105DocPreparFee3',

  // 1106 Notary Fee (8 fields)
  'origination_fees.1106_notary_fee_payable_to': 'of_fe_1106NotaryFeePayabl',
  'origination_fees.1106_notary_fee_d': 'of_fe_notaryFeeD',
  'origination_fees.1106_notary_fee_charge': 'of_fe_1106NotaryFeeCharge',
  'origination_fees.1106_notary_fee_broker': 'of_1106_not_b',
  'origination_fees.1106_notary_fee_others': 'of_1106_not_o',
  'origination_fees.1106_notary_fee_apr': 'of_fe_1106NotaryFeeApr',
  'origination_fees.1106_notary_fee_paid_to_company': 'of_fe_1106NotaryFeePaid',
  'origination_fees.1106_notary_fee_oral_disclosure': 'of_fe_1106NotaryFeeOral',

  // 1108 Title Insurance (8 fields)
  'origination_fees.1108_title_insurance_payable_to': 'of_fe_1108TitleInsuraPayabl',
  'origination_fees.1108_title_insurance_d': 'of_fe_titleInsuraD',
  'origination_fees.1108_title_insurance_charge': 'of_fe_1108TitleInsuraCharge',
  'origination_fees.1108_title_insurance_broker': 'of_1108_ti_b',
  'origination_fees.1108_title_insurance_others': 'of_1108_ti_o',
  'origination_fees.1108_title_insurance_apr': 'of_fe_1108TitleInsuraApr',
  'origination_fees.1108_title_insurance_paid_to_company': 'of_fe_1108TitleInsuraPaid',
  'origination_fees.1108_title_insurance_oral_disclosure': 'of_fe_1108TitleInsuraOral',

  // 1200 Custom Item (9 fields)
  'origination_fees.1200_custom_item_label': 'of_fe_1200CustomItemLabel',
  'origination_fees.1200_custom_item_payable_to': 'of_fe_1200CustomItemPayabl',
  'origination_fees.1200_custom_item_d': 'of_fe_1200CustomItemD',
  'origination_fees.1200_custom_item_charge': 'of_fe_1200CustomItemCharge',
  'origination_fees.1200_custom_item_broker': 'of_fe_1200CustomItemBroker',
  'origination_fees.1200_custom_item_others': 'of_fe_1200CustomItemOthers',
  'origination_fees.1200_custom_item_apr': 'of_fe_1200CustomItemApr',
  'origination_fees.1200_custom_item_paid_to_company': 'of_fe_1200CustomItemPaid',
  'origination_fees.1200_custom_item_oral_disclosure': 'of_fe_1200CustomItemOral',

  // 1201 Recording Fees (8 fields)
  'origination_fees.1201_recording_fees_payable_to': 'of_fe_1201RecordFeesPayabl',
  'origination_fees.1201_recording_fees_d': 'of_fe_recordinFeesD',
  'origination_fees.1201_recording_fees_charge': 'of_fe_1201RecordFeesCharge',
  'origination_fees.1201_recording_fees_broker': 'of_1201_rec_b',
  'origination_fees.1201_recording_fees_others': 'of_1201_rec_o',
  'origination_fees.1201_recording_fees_apr': 'of_fe_1201RecordFeesApr',
  'origination_fees.1201_recording_fees_paid_to_company': 'of_fe_1201RecordFeesPaid',
  'origination_fees.1201_recording_fees_oral_disclosure': 'of_fe_1201RecordFeesOral',

  // 1202 City/County Tax Stamps (8 fields)
  'origination_fees.1202_city_county_tax_stamps_payable_to': 'of_fe_1202CityCountyTax5',
  'origination_fees.1202_city_county_tax_stamps_d': 'of_fe_citycounTaxStampsD',
  'origination_fees.1202_city_county_tax_stamps_charge': 'of_fe_1202CityCountyTax2',
  'origination_fees.1202_city_county_tax_stamps_broker': 'of_1202_ts_b',
  'origination_fees.1202_city_county_tax_stamps_others': 'of_1202_ts_o',
  'origination_fees.1202_city_county_tax_stamps_apr': 'of_fe_1202CityCountyTax',
  'origination_fees.1202_city_county_tax_stamps_paid_to_company': 'of_fe_1202CityCountyTax4',
  'origination_fees.1202_city_county_tax_stamps_oral_disclosure': 'of_fe_1202CityCountyTax3',

  // 1301 Add This Line (9 fields)
  'origination_fees.1301_add_this_line_label': 'of_fe_1301AddThisLine',
  'origination_fees.1301_add_this_line_payable_to': 'of_fe_1301PayablTo',
  'origination_fees.1301_add_this_line_d': 'of_fe_1301Amount',
  'origination_fees.1301_add_this_line_charge': 'of_fe_1301Charge',
  'origination_fees.1301_add_this_line_broker': 'of_fe_1301Broker',
  'origination_fees.1301_add_this_line_others': 'of_fe_1301Others',
  'origination_fees.1301_add_this_line_apr': 'of_fe_1301Apr',
  'origination_fees.1301_add_this_line_paid_to_company': 'of_fe_1301PaidToCompan',
  'origination_fees.1301_add_this_line_oral_disclosure': 'of_fe_1301OralDisclo',

  // 1302 Pest Inspection (8 fields)
  'origination_fees.1302_pest_inspection_payable_to': 'of_fe_1302PestInspecPayabl',
  'origination_fees.1302_pest_inspection_d': 'of_fe_pestInspecD',
  'origination_fees.1302_pest_inspection_charge': 'of_fe_1302PestInspecCharge',
  'origination_fees.1302_pest_inspection_broker': 'of_1302_pest_b',
  'origination_fees.1302_pest_inspection_others': 'of_1302_pest_o',
  'origination_fees.1302_pest_inspection_apr': 'of_fe_1302PestInspecApr',
  'origination_fees.1302_pest_inspection_paid_to_company': 'of_fe_1302PestInspecPaid',
  'origination_fees.1302_pest_inspection_oral_disclosure': 'of_fe_1302PestInspecOral',

  // 1300 Custom Items (8 rows × 9 fields each = 72 fields)
  // Row 1
  'origination_fees.1300_custom_item_1_label': 'of_fe_1300CustomItem16',
  'origination_fees.1300_custom_item_1_payable_to': 'of_fe_1300CustomItem19',
  'origination_fees.1300_custom_item_1_d': 'of_fe_1300CustomItem12',
  'origination_fees.1300_custom_item_1_charge': 'of_fe_1300CustomItem15',
  'origination_fees.1300_custom_item_1_broker': 'of_fe_1300CustomItem1',
  'origination_fees.1300_custom_item_1_others': 'of_fe_1300CustomItem13',
  'origination_fees.1300_custom_item_1_apr': 'of_fe_1300CustomItem14',
  'origination_fees.1300_custom_item_1_paid_to_company': 'of_fe_1300CustomItem18',
  'origination_fees.1300_custom_item_1_oral_disclosure': 'of_fe_1300CustomItem17',
  // Row 2
  'origination_fees.1300_custom_item_2_label': 'of_fe_1300CustomItem26',
  'origination_fees.1300_custom_item_2_payable_to': 'of_fe_1300CustomItem29',
  'origination_fees.1300_custom_item_2_d': 'of_fe_1300CustomItem22',
  'origination_fees.1300_custom_item_2_charge': 'of_fe_1300CustomItem25',
  'origination_fees.1300_custom_item_2_broker': 'of_fe_1300CustomItem2',
  'origination_fees.1300_custom_item_2_others': 'of_fe_1300CustomItem23',
  'origination_fees.1300_custom_item_2_apr': 'of_fe_1300CustomItem24',
  'origination_fees.1300_custom_item_2_paid_to_company': 'of_fe_1300CustomItem28',
  'origination_fees.1300_custom_item_2_oral_disclosure': 'of_fe_1300CustomItem27',
  // Row 3
  'origination_fees.1300_custom_item_3_label': 'of_fe_1300CustomItem36',
  'origination_fees.1300_custom_item_3_payable_to': 'of_fe_1300CustomItem39',
  'origination_fees.1300_custom_item_3_d': 'of_fe_1300CustomItem32',
  'origination_fees.1300_custom_item_3_charge': 'of_fe_1300CustomItem35',
  'origination_fees.1300_custom_item_3_broker': 'of_fe_1300CustomItem3',
  'origination_fees.1300_custom_item_3_others': 'of_fe_1300CustomItem33',
  'origination_fees.1300_custom_item_3_apr': 'of_fe_1300CustomItem34',
  'origination_fees.1300_custom_item_3_paid_to_company': 'of_fe_1300CustomItem38',
  'origination_fees.1300_custom_item_3_oral_disclosure': 'of_fe_1300CustomItem37',
  // Row 4
  'origination_fees.1300_custom_item_4_label': 'of_fe_1300CustomItem46',
  'origination_fees.1300_custom_item_4_payable_to': 'of_fe_1300CustomItem49',
  'origination_fees.1300_custom_item_4_d': 'of_fe_1300CustomItem42',
  'origination_fees.1300_custom_item_4_charge': 'of_fe_1300CustomItem45',
  'origination_fees.1300_custom_item_4_broker': 'of_fe_1300CustomItem4',
  'origination_fees.1300_custom_item_4_others': 'of_fe_1300CustomItem43',
  'origination_fees.1300_custom_item_4_apr': 'of_fe_1300CustomItem44',
  'origination_fees.1300_custom_item_4_paid_to_company': 'of_fe_1300CustomItem48',
  'origination_fees.1300_custom_item_4_oral_disclosure': 'of_fe_1300CustomItem47',
  // Row 5
  'origination_fees.1300_custom_item_5_label': 'of_fe_1300CustomItem56',
  'origination_fees.1300_custom_item_5_payable_to': 'of_fe_1300CustomItem59',
  'origination_fees.1300_custom_item_5_d': 'of_fe_1300CustomItem52',
  'origination_fees.1300_custom_item_5_charge': 'of_fe_1300CustomItem55',
  'origination_fees.1300_custom_item_5_broker': 'of_fe_1300CustomItem5',
  'origination_fees.1300_custom_item_5_others': 'of_fe_1300CustomItem53',
  'origination_fees.1300_custom_item_5_apr': 'of_fe_1300CustomItem54',
  'origination_fees.1300_custom_item_5_paid_to_company': 'of_fe_1300CustomItem58',
  'origination_fees.1300_custom_item_5_oral_disclosure': 'of_fe_1300CustomItem57',
  // Row 6
  'origination_fees.1300_custom_item_6_label': 'of_fe_1300CustomItem66',
  'origination_fees.1300_custom_item_6_payable_to': 'of_fe_1300CustomItem69',
  'origination_fees.1300_custom_item_6_d': 'of_fe_1300CustomItem62',
  'origination_fees.1300_custom_item_6_charge': 'of_fe_1300CustomItem65',
  'origination_fees.1300_custom_item_6_broker': 'of_fe_1300CustomItem6',
  'origination_fees.1300_custom_item_6_others': 'of_fe_1300CustomItem63',
  'origination_fees.1300_custom_item_6_apr': 'of_fe_1300CustomItem64',
  'origination_fees.1300_custom_item_6_paid_to_company': 'of_fe_1300CustomItem68',
  'origination_fees.1300_custom_item_6_oral_disclosure': 'of_fe_1300CustomItem67',
  // Row 7
  'origination_fees.1300_custom_item_7_label': 'of_fe_1300CustomItem76',
  'origination_fees.1300_custom_item_7_payable_to': 'of_fe_1300CustomItem79',
  'origination_fees.1300_custom_item_7_d': 'of_fe_1300CustomItem72',
  'origination_fees.1300_custom_item_7_charge': 'of_fe_1300CustomItem75',
  'origination_fees.1300_custom_item_7_broker': 'of_fe_1300CustomItem7',
  'origination_fees.1300_custom_item_7_others': 'of_fe_1300CustomItem73',
  'origination_fees.1300_custom_item_7_apr': 'of_fe_1300CustomItem74',
  'origination_fees.1300_custom_item_7_paid_to_company': 'of_fe_1300CustomItem78',
  'origination_fees.1300_custom_item_7_oral_disclosure': 'of_fe_1300CustomItem77',
  // Row 8
  'origination_fees.1300_custom_item_8_label': 'of_fe_1300CustomItem86',
  'origination_fees.1300_custom_item_8_payable_to': 'of_fe_1300CustomItem89',
  'origination_fees.1300_custom_item_8_d': 'of_fe_1300CustomItem82',
  'origination_fees.1300_custom_item_8_charge': 'of_fe_1300CustomItem85',
  'origination_fees.1300_custom_item_8_broker': 'of_fe_1300CustomItem8',
  'origination_fees.1300_custom_item_8_others': 'of_fe_1300CustomItem83',
  'origination_fees.1300_custom_item_8_apr': 'of_fe_1300CustomItem84',
  'origination_fees.1300_custom_item_8_paid_to_company': 'of_fe_1300CustomItem88',
  'origination_fees.1300_custom_item_8_oral_disclosure': 'of_fe_1300CustomItem87',

  // Subtotals and Totals
  'origination_fees.subtotal_j': 'of_fe_subtotalJ',
  'origination_fees.subtotal_others': 'of_fe_subtotalOthers',
  'origination_fees.total_j': 'of_fe_totalJ',

  // Compensation to Broker
  'origination_fees.commission_fees_d': 'of_fe_commissiFeesD',
  'origination_fees.additional_compensation_d': 'of_fe_additionCompenD',

  // Payment of Other Obligations
  'origination_fees.credit_life_disability_insurance_label': 'of_fe_creditLifediInsuraLabel',
  'origination_fees.loan_documentation_fee_d': 'of_fe_loanDocumeFeeD',
  'origination_fees.custom_other_obligation_label': 'of_fe_customOtherObligaLabel',
  'origination_fees.custom_other_obligation_d': 'of_fe_customOtherObligaD',

  // Payment to Existing Liens
  'origination_fees.existing_lien_1_label': 'of_fe_existingLien1Label',
  'origination_fees.existing_lien_1_d': 'of_fe_existingLien1D',
  'origination_fees.existing_lien_2_label': 'of_fe_existingLien2Label',
  'origination_fees.existing_lien_2_d': 'of_fe_existingLien2D',
  'origination_fees.existing_lien_3_label': 'of_fe_existingLien3Label',
  'origination_fees.existing_lien_3_d': 'of_fe_existingLien3D',

  // ──────────────────────────────────────────────────
  // RE 885 PROPOSED LOAN TERMS
  // ──────────────────────────────────────────────────
  'origination_fees.re885_proposed_loan_amount': 'of_re_proposedLoanAmount',
  'origination_fees.re885_initial_fees_page1': 'of_re_initialFeesPage1',
  'origination_fees.re885_other_obligations': 'of_re_otherObligations',
  'origination_fees.re885_credit_life_insurance': 'of_re_creditLifeInsurance',
  'origination_fees.re885_additional_obligation_1': 'of_re_additionalObligation1',
  'origination_fees.re885_additional_obligation_2': 'of_re_additionalObligation2',
  'origination_fees.re885_subtotal_deductions': 'of_re_subtotalDeductions',
  'origination_fees.re885_cash_at_closing_option': 'of_re_cashAtClosingOption',
  'origination_fees.re885_cash_at_closing_amount': 'of_re_cashAtClosingAmount',
  'origination_fees.re885_loan_term_value': 'of_re_loanTermValue',
  'origination_fees.re885_loan_term_unit': 'of_re_loanTermUnit',
  'origination_fees.re885_interest_rate': 'of_re_interestRate',
  'origination_fees.re885_rate_type_fixed': 'of_re_rateTypeFixed',
  'origination_fees.re885_rate_type_adjustable': 'of_re_rateTypeAdjustable',
  'origination_fees.re885_iv_adj_rate_months': 'of_re_ivAdjRateMonths',
  'origination_fees.re885_v_fully_indexed_rate': 'of_re_vFullyIndexedRate',
  'origination_fees.re885_vi_max_interest_rate': 'of_re_viMaxInterestRate',
  'origination_fees.re885_vii_payment_amount': 'of_re_viiPaymentAmount',
  'origination_fees.re885_viii_rate_increase_pct': 'of_re_viiiRateIncreasePct',
  'origination_fees.re885_viii_rate_increase_months': 'of_re_viiiRateIncreaseMonths',
  'origination_fees.re885_ix_payment_end_months': 'of_re_ixPaymentEndMonths',
  'origination_fees.re885_ix_payment_end_pct': 'of_re_ixPaymentEndPct',
  'origination_fees.re885_xi_neg_amort_balance': 'of_re_xiNegAmortBalance',
  'origination_fees.re885_impound_county_taxes': 'of_re_impoundCountyTaxes',
  'origination_fees.re885_impound_hazard_ins': 'of_re_impoundHazardIns',
  'origination_fees.re885_impound_mortgage_ins': 'of_re_impoundMortgageIns',
  'origination_fees.re885_impound_flood_ins': 'of_re_impoundFloodIns',
  'origination_fees.re885_impound_other': 'of_re_impoundOther',
  'origination_fees.re885_impound_other_desc': 'of_re_impoundOtherDesc',
  'origination_fees.re885_impound_approx_amount': 'of_re_impoundApproxAmount',

  // Other Origination Fee fields (Interest, Hazard, Mortgage Ins, Property Taxes)
  'origination_fees.interest_days': 'of_int_days',
  'origination_fees.interest_per_day': 'of_int_pd',
  'origination_fees.hazard_insurance_months': 'of_haz_mon',
  'origination_fees.hazard_insurance_monthly_amount': 'of_haz_amt',
  'origination_fees.mortgage_insurance_months': 'of_mi_mon',
  'origination_fees.mortgage_insurance_monthly_amount': 'of_mi_amt',
  'origination_fees.property_taxes_months': 'of_tax_mon',
  'origination_fees.property_taxes_monthly_amount': 'of_tax_amt',

  // ──────────────────────────────────────────────────
  // INSURANCE
  // ──────────────────────────────────────────────────
  'insurance1.property': 'in_d_property',
  'insurance1.description': 'in_d_description',
  'insurance1.insured_name': 'in_d_insuredName',
  'insurance1.company_name': 'in_d_companyName',
  'insurance1.policy_number': 'in_d_policyNumber',
  'insurance1.expiration': 'in_d_expiration',
  'insurance1.coverage': 'in_d_coverage',
  'insurance1.active': 'in_d_active',
  'insurance1.agent_name': 'in_d_agentName',
  'insurance1.business_address': 'in_d_businessAddress',
  'insurance1.business_address_city': 'in_d_businessAddressCity',
  'insurance1.business_address_state': 'in_d_businessAddressState',
  'insurance1.business_address_zip': 'in_d_businessAddressZip',
  'insurance1.phone_number': 'in_d_phoneNumber',
  'insurance1.fax_number': 'in_d_faxNumber',
  'insurance1.email': 'in_d_email',
  'insurance1.note': 'in_d_note',
  'insurance1.payment_mailing_street': 'in_d_paymentMailingStreet',
  'insurance1.payment_mailing_city': 'in_d_paymentMailingCity',
  'insurance1.payment_mailing_state': 'in_d_paymentMailingState',
  'insurance1.payment_mailing_zip': 'in_d_paymentMailingZip',
  'insurance1.insurance_tracking': 'in_d_insuranceTracking',
  'insurance1.last_verified': 'in_d_lastVerified',
  'insurance1.tracking_status': 'in_d_trackingStatus',
  // Canonical (numberless) entries for getCanonicalKey resolution
  'insurance.property': 'in_d_property',
  'insurance.description': 'in_d_description',
  'insurance.insured_name': 'in_d_insuredName',
  'insurance.company_name': 'in_d_companyName',
  'insurance.policy_number': 'in_d_policyNumber',
  'insurance.expiration': 'in_d_expiration',
  'insurance.coverage': 'in_d_coverage',
  'insurance.active': 'in_d_active',
  'insurance.agent_name': 'in_d_agentName',
  'insurance.business_address': 'in_d_businessAddress',
  'insurance.business_address_city': 'in_d_businessAddressCity',
  'insurance.business_address_state': 'in_d_businessAddressState',
  'insurance.business_address_zip': 'in_d_businessAddressZip',
  'insurance.phone_number': 'in_d_phoneNumber',
  'insurance.fax_number': 'in_d_faxNumber',
  'insurance.email': 'in_d_email',
  'insurance.note': 'in_d_note',
  'insurance.payment_mailing_street': 'in_d_paymentMailingStreet',
  'insurance.payment_mailing_city': 'in_d_paymentMailingCity',
  'insurance.payment_mailing_state': 'in_d_paymentMailingState',
  'insurance.payment_mailing_zip': 'in_d_paymentMailingZip',
  'insurance.insurance_tracking': 'in_d_insuranceTracking',
  'insurance.last_verified': 'in_d_lastVerified',
  'insurance.tracking_status': 'in_d_trackingStatus',

  // ──────────────────────────────────────────────────
  // NOTES / CONVERSATION LOG
  // ──────────────────────────────────────────────────
  'notes_entry.high_priority': 'nt_p_highPriori',
  'notes_entry.date': 'nt_p_date',
  'notes_entry.as_of_date': 'nt_p_asOf',
  'notes_entry.account': 'nt_p_account',
  'notes_entry.name': 'nt_p_name',
  'notes_entry.reference': 'nt_p_referenc',
  'notes_entry.content': 'nt_p_content',
  'notes_entry.type': 'nt_p_type',
  'notes_entry.attachments': 'nt_p_attachments',
  'notes_entry.meta': 'nt_p_notes',

  // ──────────────────────────────────────────────────
  // ORIGINATION APPLICATION
  // ──────────────────────────────────────────────────
  'origination_app.doc.is_broker_also_borrower_yes': 'or_p_isBrokerAlsoBorrower_yes',
};

// Build reverse map: DB key → legacy key (for hydration)
export const DB_KEY_TO_LEGACY: Record<string, string> = {};
// Only map the first (canonical) legacy key for each DB key
const _seenDbKeys = new Set<string>();
for (const [legacy, db] of Object.entries(LEGACY_TO_DB_KEY)) {
  if (!_seenDbKeys.has(db)) {
    DB_KEY_TO_LEGACY[db] = legacy;
    _seenDbKeys.add(db);
  }
}

/**
 * Resolve a legacy dot-notation key to its DB field_key.
 * Returns the DB key if found, otherwise the original key unchanged.
 */
export function resolveLegacyKey(legacyKey: string): string {
  return LEGACY_TO_DB_KEY[legacyKey] || legacyKey;
}

/**
 * Resolve a DB field_key back to its legacy dot-notation key.
 * Returns the legacy key if found, otherwise the original key unchanged.
 */
export function resolveDbKeyToLegacy(dbKey: string): string {
  return DB_KEY_TO_LEGACY[dbKey] || dbKey;
}
