/**
 * Legacy Key Map
 * 
 * Maps legacy dot-notation field keys (used in fieldKeyMap.ts and SectionContent files)
 * to actual DB field_dictionary field_key values (br_p_firstName convention).
 * 
 * This translation layer ensures data persistence works without requiring
 * a massive refactor of 30+ UI files that use the legacy dot-notation convention.
 * 
 * The map is used by useDealFields.ts during save/load to resolve field_dictionary entries.
 */

export const LEGACY_TO_DB_KEY: Record<string, string> = {
  // ──────────────────────────────────────────────────
  // BORROWER PRIMARY
  // ──────────────────────────────────────────────────
  'borrower.borrower_type': 'br_p_borrowerType',
  'borrower.borrower_id': 'br_p_borrowerId',
  'borrower.full_name': 'br_p_fullName',
  'borrower.first_name': 'br_p_firstName',
  'borrower.middle_initial': 'br_p_middleInitia',
  'borrower.last_name': 'br_p_lastName',
  'borrower.capacity': 'br_p_capacity',
  'borrower.email': 'br_p_emailAddres',
  'borrower.credit_score': 'br_p_creditScore',
  'borrower.issue_1098': 'br_p_issue1098',
  'borrower.alternate_reporting': 'br_p_alternatReport',
  'borrower.tax_id_type': 'br_p_taxIdType',
  'borrower.tin': 'br_p_tin',
  'borrower.tin_verified': 'br_p_tinVerifi',
  'borrower.is_primary': 'br_p_isPrimar',
  'borrower.address.street': 'br_p_address',
  'borrower.address.city': 'br_p_borrowerCity',
  'borrower.state': 'br_p_state2',
  'borrower.address.zip': 'br_p_zip',
  'borrower.mailing_same_as_primary': 'br_p_mailingSameAsPrimar',
  'borrower.mailing.street': 'br_p_mailingStreet',
  'borrower.mailing.city': 'br_p_mailingCity',
  'borrower.mailing.state': 'br_p_mailingState',
  'borrower.mailing.zip': 'br_p_mailingZip',
  'borrower.phone.home': 'br_p_homePhone',
  'borrower.phone.work': 'br_p_workPhone',
  'borrower.phone.mobile': 'br_p_cellPhone',
  'borrower.phone.fax': 'br_p_fax',
  'borrower.preferred.home': 'br_p_preferreHome',
  'borrower.preferred.work': 'br_p_preferreWork',
  'borrower.preferred.cell': 'br_p_preferreCell',
  'borrower.preferred.fax': 'br_p_preferreFax',
  'borrower.delivery_print': 'br_p_deliveryPrint',
  'borrower.delivery_email': 'br_p_deliveryEmail',
  'borrower.delivery_sms': 'br_p_deliverySms',
  'borrower.delivery_online': 'br_p_deliveryOnline',
  'borrower.delivery_mail': 'br_p_deliveryMail',
  'borrower.send_payment_notification': 'br_p_sendPaymenNotifi',
  'borrower.send_late_notice': 'br_p_sendLateNotice',
  'borrower.send_borrower_statement': 'br_p_sendBorrowStatem',
  'borrower.send_maturity_notice': 'br_p_sendMaturiNotice',
  'borrower.vesting': 'br_p_vestin',
  'borrower.ford.1': 'br_p_ford1',
  'borrower.ford.2': 'br_p_ford2',
  'borrower.ford.3': 'br_p_ford3',
  'borrower.ford.4': 'br_p_ford4',
  'borrower.ford.5': 'br_p_ford5',
  'borrower.ford.6': 'br_p_ford6',
  'borrower.ford.7': 'br_p_ford7',
  'borrower.ford.8': 'br_p_ford8',
  'borrower.note': 'br_p_note',
  'borrower.description': 'br_p_borrowerDescri',

  // BORROWER AUTHORIZED PARTY
  'borrower.authorized_party.first_name': 'br_p_authPartyFirstName',
  'borrower.authorized_party.middle_name': 'br_p_authPartyMiddleName',
  'borrower.authorized_party.last_name': 'br_p_authPartyLastName',
  'borrower.authorized_party.capacity': 'br_p_authPartyCapaci',
  'borrower.authorized_party.email': 'br_p_authPartyEmail',
  'borrower.authorized_party.address.street': 'br_p_authPartyStreet',
  'borrower.authorized_party.address.city': 'br_p_authPartyCity',
  'borrower.authorized_party.address.state': 'br_p_authPartyState',
  'borrower.authorized_party.address.zip': 'br_p_authPartyZip',
  'borrower.authorized_party.phone.home': 'br_p_authPartyHomePhone',
  'borrower.authorized_party.phone.work': 'br_p_authPartyWorkPhone',
  'borrower.authorized_party.phone.cell': 'br_p_authPartyCellPhone',
  'borrower.authorized_party.phone.fax': 'br_p_authPartyFax',
  'borrower.authorized_party.send_pref.payment_notification': 'br_p_authPartySendPaymen',
  'borrower.authorized_party.send_pref.late_notice': 'br_p_authPartySendLate',
  'borrower.authorized_party.send_pref.borrower_statement': 'br_p_authPartySendBorrow',
  'borrower.authorized_party.send_pref.maturity_notice': 'br_p_authPartySendMaturi',
  'borrower.authorized_party.delivery.email': 'br_p_authPartyDeliveEmail',
  'borrower.authorized_party.delivery.mail': 'br_p_authPartyDeliveMail',
  'borrower.authorized_party.delivery.sms': 'br_p_authPartyDeliveSms',
  'borrower.authorized_party.details': 'br_p_authPartyDetail',

  // BORROWER BANKING (ACH)
  'ach.bank_name': 'br_p_bankName',
  'ach.bank_address': 'br_p_bankAddres',
  'ach.routing_number': 'br_p_routingNumber',
  'ach.account_number': 'br_p_accountNumber',
  'ach.individual_id': 'br_p_individId',
  'ach.individual_name': 'br_p_individName',
  'ach.account_type': 'br_p_accountType',
  'ach.service_status': 'br_p_serviceStatus',
  'ach.apply_debit_as': 'br_p_applyDebitAs',
  'ach.debit_frequency': 'br_p_debitFreque',
  'ach.debit_due_day': 'br_p_debitDueDay',
  'ach.next_debit_date': 'br_p_nextDebitDate',
  'ach.stop_date': 'br_p_stopDate',
  'ach.debit_amount': 'br_p_debitAmount',
  'ach.send_confirm': 'br_p_sendConfir',
  'ach.disable_online_payment': 'br_p_disableOnlinePaymen',

  // BORROWER TAX DETAIL (1098)
  'borrower.1098.designated_recipient': 'br_t_designatRecipi',
  'borrower.1098.name': 'br_t_name',
  'borrower.1098.address': 'br_t_address',
  'borrower.1098.account_number': 'br_t_accountNumber',
  'borrower.1098.city': 'br_t_city',
  'borrower.1098.tin_type': 'br_t_tinType',
  'borrower.1098.tin': 'br_t_tin',
  'borrower.1098.state': 'br_t_state',
  'borrower.1098.zip': 'br_t_zip',
  'borrower.1098.send_1098': 'br_p_send1098',

  // BORROWER GUARANTOR
  'borrower.guarantor.borrower_type': 'br_p_guarantoBorrowType',
  'borrower.guarantor.borrower_id': 'br_p_guarantoBorrowId',
  'borrower.guarantor.full_name': 'br_p_guarantoFullName',
  'borrower.guarantor.first_name': 'br_p_guarantoFirstName',
  'borrower.guarantor.middle_initial': 'br_p_guarantoMiddleInitia',
  'borrower.guarantor.last_name': 'br_p_guarantoLastName',
  'borrower.guarantor.capacity': 'br_p_guarantoCapaci',
  'borrower.guarantor.email': 'br_p_guarantoEmail',
  'borrower.guarantor.credit_score': 'br_p_guarantoCreditScore',
  'borrower.guarantor.issue_1098': 'br_p_guarantoIssue1098',
  'borrower.guarantor.alternate_reporting': 'br_p_guarantoAlternReport',
  'borrower.guarantor.tax_id_type': 'br_p_guarantoTaxIdType',
  'borrower.guarantor.tin': 'br_p_guarantoTaxId',
  'borrower.guarantor.tin_verified': 'br_p_guarantoTinVerifi',
  'borrower.guarantor.address.street': 'br_p_guarantoStreet',
  'borrower.guarantor.address.city': 'br_p_guarantoCity',
  'borrower.guarantor.state': 'br_p_guarantoState',
  'borrower.guarantor.address.zip': 'br_p_guarantoZip',
  'borrower.guarantor.mailing_same_as_primary': 'br_p_guarantoMailinSameAs',
  'borrower.guarantor.mailing.street': 'br_p_guarantoMailinStreet',
  'borrower.guarantor.mailing.city': 'br_p_guarantoMailinCity',
  'borrower.guarantor.mailing.state': 'br_p_guarantoMailinState',
  'borrower.guarantor.mailing.zip': 'br_p_guarantoMailinZip',
  'borrower.guarantor.phone.home': 'br_p_guarantoHomePhone',
  'borrower.guarantor.phone.work': 'br_p_guarantoWorkPhone',
  'borrower.guarantor.phone.mobile': 'br_p_guarantoCellPhone',
  'borrower.guarantor.phone.fax': 'br_p_guarantoFax',
  'borrower.guarantor.preferred.home': 'br_p_guarantoPreferHome',
  'borrower.guarantor.preferred.work': 'br_p_guarantoPreferWork',
  'borrower.guarantor.preferred.cell': 'br_p_guarantoPreferCell',
  'borrower.guarantor.preferred.fax': 'br_p_guarantoPreferFax',
  'borrower.guarantor.delivery_print': 'br_p_guarantoDelivePrint',
  'borrower.guarantor.delivery_email': 'br_p_guarantoDeliveEmail',
  'borrower.guarantor.delivery_sms': 'br_p_guarantoDeliveSms',
  'borrower.guarantor.send_payment_notification': 'br_p_guarantoSendPaymen',
  'borrower.guarantor.send_late_notice': 'br_p_guarantoSendLate',
  'borrower.guarantor.send_borrower_statement': 'br_p_guarantoSendBorrow',
  'borrower.guarantor.send_maturity_notice': 'br_p_guarantoSendMaturi',
  'borrower.guarantor.delivery_online': 'br_p_guarantoDeliveOnline',
  'borrower.guarantor.delivery_mail': 'br_p_guarantoDeliveMail',
  'borrower.guarantor.vesting': 'br_p_guarantoVestin',
  'borrower.guarantor.vesting_overridden': 'br_p_guarantoVestinOverri',
  'borrower.guarantor.ford.1': 'br_p_guarantoFord1',
  'borrower.guarantor.ford.2': 'br_p_guarantoFord2',
  'borrower.guarantor.ford.3': 'br_p_guarantoFord3',
  'borrower.guarantor.ford.4': 'br_p_guarantoFord4',
  'borrower.guarantor.ford.5': 'br_p_guarantoFord5',
  'borrower.guarantor.ford.6': 'br_p_guarantoFord6',
  'borrower.guarantor.ford.7': 'br_p_guarantoFord7',
  'borrower.guarantor.ford.8': 'br_p_guarantoFord8',

  // ──────────────────────────────────────────────────
  // CO-BORROWER
  // ──────────────────────────────────────────────────
  'coborrower.full_name': 'cb_p_coborrowFullName',
  'coborrower.first_name': 'cb_p_coborrowFirstName',
  'coborrower.middle_name': 'cb_p_coborrowMiddleName',
  'coborrower.last_name': 'cb_p_coborrowLastName',
  'coborrower.salutation': 'cb_p_coborrowSaluta',
  'coborrower.generation': 'cb_p_coborrowGenera',
  'coborrower.email': 'cb_p_coborrowEmail',
  'coborrower.phone.home': 'cb_p_coborrowHomePhone',
  'coborrower.phone.work': 'cb_p_coborrowWorkPhone',
  'coborrower.phone.mobile': 'cb_p_coborrowCellPhone',
  'coborrower.fax': 'cb_p_coborrowFax',
  'coborrower.preferred.home': 'cb_p_preferreHome',
  'coborrower.preferred.work': 'cb_p_preferreWork',
  'coborrower.preferred.cell': 'cb_p_preferreCell',
  'coborrower.preferred.fax': 'cb_p_preferreFax',
  'coborrower.address.street': 'cb_p_coborrowStreet',
  'coborrower.address.city': 'cb_p_coborrowCity',
  'coborrower.state': 'cb_p_coborrowState',
  'coborrower.address.zip': 'cb_p_coborrowZip',
  'coborrower.primary_address.street': 'cb_p_primaryAddresStreet',
  'coborrower.primary_address.city': 'cb_p_primaryAddresCity',
  'coborrower.primary_address.state': 'cb_p_primaryAddresState',
  'coborrower.primary_address.zip': 'cb_p_primaryAddresZip',
  'coborrower.mailing_address.street': 'cb_p_mailingAddresStreet',
  'coborrower.mailing_address.city': 'cb_p_mailingAddresCity',
  'coborrower.mailing_address.state': 'cb_p_mailingAddresState',
  'coborrower.mailing_address.zip': 'cb_p_mailingAddresZip',
  'coborrower.mailing_same_as_primary': 'cb_p_sameAsPrimar',
  'coborrower.is_primary': 'cb_p_primaryContac',
  'coborrower.loan_number': 'cb_p_loanNumber',
  'coborrower.tin': 'cb_p_tin',
  'coborrower.relation': 'cb_p_relation',
  'coborrower.type': 'cb_p_borrowerType',
  'coborrower.borrower_id': 'cb_p_borrowerId',
  'coborrower.borrower_type': 'cb_p_borrowerType2',
  'coborrower.capacity': 'cb_p_capacity',
  'coborrower.credit_score': 'cb_p_creditScore',
  'coborrower.vesting': 'cb_p_vestin',
  'coborrower.ford': 'cb_p_ford',
  'coborrower.ford1': 'cb_p_ford1',
  'coborrower.ford2': 'cb_p_ford2',
  'coborrower.ford3': 'cb_p_ford3',
  'coborrower.ford4': 'cb_p_ford4',
  'coborrower.ford5': 'cb_p_ford5',
  'coborrower.ford6': 'cb_p_ford6',
  'coborrower.ford7': 'cb_p_ford7',
  'coborrower.ford8': 'cb_p_ford8',
  'coborrower.issue_1098': 'cb_p_issue1098',
  'coborrower.alternate_reporting': 'cb_p_alternatReport',
  'coborrower.delivery_online': 'cb_p_deliveryOnline',
  'coborrower.delivery_mail': 'cb_p_deliveryMail',
  'coborrower.dob': 'cb_p_dob',
  'coborrower.credit_reporting': 'cb_p_creditReportEnable',
  'coborrower.res_code': 'cb_p_coborrowResCode',
  'coborrower.address_indicator': 'cb_p_coborrowAddresIndica',
  'coborrower.send_borrower_notifications': 'cb_p_sendBorrowNotifi',
  'coborrower.format': 'cb_p_coborrowEmailFormat',
  'coborrower.delivery_print': 'cb_p_coborrowDelivePrint',
  'coborrower.delivery_email': 'cb_p_coborrowDeliveEmail',
  'coborrower.delivery_sms': 'cb_p_coborrowDeliveSms',
  'coborrower.tax_id_type': 'cb_p_taxIdType',
  'coborrower.tin_verified': 'cb_p_tinVerifi',
  'coborrower.send_payment_notification': 'cb_p_sendPaymenNotifi',
  'coborrower.send_late_notice': 'cb_p_sendLateNotice',
  'coborrower.send_borrower_statement': 'cb_p_sendBorrowStatem',
  'coborrower.send_maturity_notice': 'cb_p_sendMaturiNotice',
  'coborrower.parent_borrower_prefix': 'cb_p_parentBorrowPrefix',

  // ──────────────────────────────────────────────────
  // LENDER INFO
  // ──────────────────────────────────────────────────
  'lender.type': 'ld_p_lenderType',
  'lender.lender_id': 'ld_p_lenderId',
  'lender.full_name': 'ld_p_fullName',
  'lender.first_name': 'ld_p_firstName',
  'lender.middle_name': 'ld_p_middleName',
  'lender.last_name': 'ld_p_lastName',
  'lender.capacity': 'ld_p_capacity',
  'lender.email': 'ld_p_email',
  'lender.tax_id_type': 'ld_p_taxIdType',
  'lender.tax_id': 'ld_p_taxId',
  'lender.issue_1099': 'ld_p_issue1099',
  'lender.prepare_ca_881': 'ld_p_prepareCa881',
  'lender.taxed_as': 'ld_p_taxedAs',
  'lender.lp_lllp_llc_taxed_as_corp': 'ld_p_lpLllpLlcTaxedAsCorp',
  'lender.tin_verified': 'ld_p_tinVerifi',
  'lender.alternate_reporting': 'ld_p_alternatReport',
  'lender.is_primary': 'ld_p_isPrimar',
  'lender.isPrimary': 'ld_p_isPrimar',
  'lender.primary_address.street': 'ld_p_street',
  'lender.primary_address.city': 'ld_p_city',
  'lender.primary_address.state': 'ld_p_state',
  'lender.primary_address.zip': 'ld_p_zip',
  'lender.phone.home': 'ld_p_homePhone',
  'lender.phone.work': 'ld_p_workPhone',
  'lender.phone.cell': 'ld_p_cellPhone',
  'lender.phone.fax': 'ld_p_fax',
  'lender.send_pref.payment_notification': 'ld_p_paymentNotifi',
  'lender.send_pref.late_notice': 'ld_p_lateNotice',
  'lender.send_pref.borrower_statement': 'ld_p_borrowerStatem',
  'lender.send_pref.maturity_notice': 'ld_p_maturityNotice',
  'lender.preferred.home': 'ld_p_preferreHome',
  'lender.preferred.work': 'ld_p_preferreWork',
  'lender.preferred.cell': 'ld_p_preferreCell',
  'lender.preferred.fax': 'ld_p_preferreFax',
  'lender.care_of.street': 'ld_p_careOfStreet',
  'lender.care_of.city': 'ld_p_careOfCity',
  'lender.care_of.state': 'ld_p_careOfState',
  'lender.care_of.zip': 'ld_p_careOfZip',
  'lender.vesting': 'ld_p_vestin',
  'lender.ford.1': 'ld_p_ford1',
  'lender.ford.2': 'ld_p_ford2',
  'lender.ford.3': 'ld_p_ford3',
  'lender.ford.4': 'ld_p_ford4',
  'lender.ford.5': 'ld_p_ford5',
  'lender.ford.6': 'ld_p_ford6',
  'lender.ford.7': 'ld_p_ford7',
  'lender.ford.8': 'ld_p_ford8',
  'lender.loan_id': 'ld_p_loanId',
  'lender.loan_type': 'ld_p_loanType',
  'lender.delivery.print': 'ld_p_deliveryPrint',
  'lender.delivery.email': 'ld_p_deliveryEmailLender',
  'lender.delivery.sms': 'ld_p_deliverySmsLender',
  'lender.dob': 'ld_p_dob',
  'lender.mailing.street': 'ld_p_mailingStreet',
  'lender.mailing.city': 'ld_p_mailingCity',
  'lender.mailing.state': 'ld_p_mailingState',
  'lender.mailing.zip': 'ld_p_mailingZip',
  'lender.mailing_same_as_primary': 'ld_p_mailingSameAsPrimar',
  'lender.servicing_agreement_on_file': 'ld_p_servicinAgreem',
  'lender.freeze_outgoing_disbursements': 'ld_p_freezeOutgoi',
  'lender.investor_questionnaire_due': 'ld_p_investoQuesti',
  'lender.investor_questionnaire_due_date': 'ld_p_investoQuestiDueDate',

  // LENDER AUTHORIZED PARTY
  'lender.authorized_party.first_name': 'ld_ap_firstName',
  'lender.authorized_party.middle_name': 'ld_ap_middleName',
  'lender.authorized_party.last_name': 'ld_ap_lastName',
  'lender.authorized_party.capacity': 'ld_ap_authorizPartyCapaci',
  'lender.authorized_party.email': 'ld_ap_email',
  'lender.authorized_party.send_pref.payment_notification': 'ld_ap_paymentNotifi',
  'lender.authorized_party.send_pref.late_notice': 'ld_ap_lateNotice',
  'lender.authorized_party.send_pref.maturity_notice': 'ld_ap_maturityNotice',
  'lender.authorized_party.send_pref.borrower_statement': 'ld_ap_borrowerStatem',
  'lender.authorized_party.address.street': 'ld_ap_street',
  'lender.authorized_party.address.city': 'ld_ap_city',
  'lender.authorized_party.address.state': 'ld_ap_state',
  'lender.authorized_party.address.zip': 'ld_ap_zip',
  'lender.authorized_party.address.details': 'ld_ap_authorizPartyAddresDetail',
  'lender.authorized_party.phone.home': 'ld_ap_homePhone',
  'lender.authorized_party.phone.work': 'ld_ap_workPhone',
  'lender.authorized_party.phone.cell': 'ld_ap_cellPhone',
  'lender.authorized_party.phone.fax': 'ld_ap_fax',
  'lender.authorized_party.delivery.email': 'ld_ap_deliveryEmail',
  'lender.authorized_party.delivery.mail': 'ld_ap_deliveryMail',
  'lender.authorized_party.delivery.sms': 'ld_ap_deliverySms',

  // LENDER BANKING
  'lender.banking.ach_status': 'ld_p_achStatus',
  'lender.banking.bank': 'ld_p_bank',
  'lender.banking.routing_number': 'ld_b_routingNumber',
  'lender.banking.account_number': 'ld_p_accountNumber',
  'lender.banking.account_type': 'ld_p_accountType',
  'lender.banking.account_name': 'ld_p_accountName',
  'lender.banking.account_id': 'ld_p_accountId',
  'lender.banking.further_credit_to': 'ld_p_furtherCreditTo',
  'lender.banking.by_check': 'ld_p_byCheck',
  'lender.banking.check_same_as_mailing': 'ld_p_checkSameAsMailing',
  'lender.banking.address': 'ld_p_checkAddres',
  'lender.banking.city': 'ld_p_checkCity',
  'lender.banking.zip_code': 'ld_p_checkZip',
  'lender.banking.ach_email': 'ld_p_achEmail',
  'lender.banking.ach_email_2': 'ld_p_achEmail2',
  'lender.banking.cc_name': 'ld_p_creditCardName',
  'lender.banking.cc_number': 'ld_p_cardNumber',
  'lender.banking.cc_security_code': 'ld_p_securityCode',
  'lender.banking.cc_expiration': 'ld_p_expirati',
  'lender.banking.cc_zip': 'ld_p_creditCardZip',

  // LENDER TAX INFO
  'lender.tax_payer.designated_recipient': 'ld_p_designatRecipi',
  'lender.tax_payer.name': 'ld_p_taxPayerName',
  'lender.tax_payer.street_address': 'ld_p_taxPayerStreetAddres',
  'lender.tax_payer.account_number': 'ld_b_taxPayerAccounNumber',
  'lender.tax_payer.city': 'ld_p_taxPayerCity',
  'lender.tax_payer.recipient_type': 'ld_p_taxPayerRecipiType',
  'lender.tax_payer.ssn': 'ld_p_taxPayerSsn',
  'lender.tax_payer.state': 'ld_p_taxPayerState',
  'lender.tax_payer.zip_code': 'ld_p_taxPayerZipCode',
  'lender.tax_payer.auto_synchronize': 'ld_p_taxPayerAutoSynchr',

  // ──────────────────────────────────────────────────
  // LOAN TERMS
  // ──────────────────────────────────────────────────
  'loan_terms.loan_amount': 'ln_p_loanAmount',
  'loan.original_amount': 'ln_p_originalAmount',
  'loan_terms.note_rate': 'ln_p_noteRate',
  'loan_terms.sold_rate': 'ln_p_soldRate',
  'loan_terms.interest_split': 'ln_p_interestSplit',
  'loan_terms.accrual_method': 'ln_p_accrualMethod',
  'loan_terms.unearned_discount_balance': 'ln_p_unearnedDiscouBalanc',
  'loan_terms.prepaid_payments': 'ln_p_prepaidPaymen',
  'loan_terms.impounded_payments': 'ln_p_impoundePaymen',
  'loan_terms.funding_holdback': 'ln_p_fundingHoldba',
  'loan_terms.number_of_payments': 'ln_p_numberOfPaymen',
  'loan_terms.payment_frequency': 'ln_p_paymentFreque',
  'loan_terms.day_due': 'ln_p_dayDue',
  'loan_terms.first_payment': 'ln_p_firstPaymen',
  'loan_terms.last_payment_received': 'ln_p_lastPaymenReceiv',
  'loan_terms.paid_to': 'ln_p_paidTo',
  'loan_terms.next_payment': 'ln_p_nextPaymen',
  'loan_terms.regular_payment': 'ln_p_regularPaymen',
  'loan_terms.additional_principal': 'ln_p_additionPrinci',
  'loan_terms.servicing_fees': 'ln_p_servicinFees',
  'loan_terms.total_payment': 'ln_p_totalPaymen',
  'loan_terms.principal': 'ln_p_principa',
  'loan_terms.unpaid_late_charges': 'ln_bl_unpaidLateCharge',
  'loan_terms.accrued_late_charges': 'ln_p_accruedLateCharge',
  'loan_terms.unpaid_interest': 'ln_bl_unpaidIntere',
  'loan_terms.accrued_interest': 'ln_p_accruedIntere',
  'loan_terms.interest_guarantee': 'ln_p_interestGuaran',
  'loan_terms.unpaid_default_interest': 'ln_bl_unpaidDefaulIntere',
  'loan_terms.accrued_default_interest': 'ln_p_accruedDefaulIntere',
  'loan_terms.charges_owed': 'ln_p_chargesOwed',
  'loan_terms.charges_interest': 'ln_p_chargesIntere',
  'loan_terms.reserve_balance': 'ln_p_reserveBalanc',
  'loan_terms.escrow_balance': 'ln_p_escrowBalanc',
  'loan_terms.total_balance_due': 'ln_p_totalBalancDue',
  'loan_terms.estimated_balloon_payment': 'ln_p_estimateBallooPaymen',
  'loan_terms.default_interest': 'ln_p_defaultIntere',
  'loan_terms.other_scheduled_payments': 'ln_p_otherScheduPaymen',
  'loan_terms.to_escrow_impounds': 'ln_p_toEscrowImpoun',
  'loan_terms.accept_short_payments_enabled': 'ln_p_acceptShortPaymen',
  'loan_terms.hold_days': 'ln_p_holdDays',
  'loan_terms.override_funds_held': 'ln_p_overrideFundsHeld',
  'loan_terms.sales_tax_enabled': 'ln_p_salesTax',
  'loan_terms.details_company': 'ln_p_company',
  'Terms.LoanNumber': 'ln_p_loanNumber',
  'loan_terms.assigned_csr': 'ln_p_assignedCsr',
  'loan_terms.details_originating_vendor': 'ln_p_originatVendor',
  'loan_terms.origination': 'ln_p_originat',
  'loan_terms.boarding': 'ln_p_boarding',
  'loan_terms.maturity': 'ln_pn_maturity',
  'loan_terms.maturity_date': 'ln_pn_maturityDate',
  'loan_terms.lien_position': 'ln_p_lienPositi',
  'loan_terms.loan_purpose': 'ln_p_loanPurpos',
  'loan_terms.rate_structure': 'ln_p_rateStruct',
  'loan_terms.amortization': 'ln_p_amortiza',
  'loan_terms.interest_calculation': 'ln_p_interestCalcul',
  'loan_terms.short_payments_applied_to': 'ln_p_shortPaymenApplieTo',
  'loan_terms.processing_unpaid_interest': 'ln_bl_processiUnpaidIntere',
  'loan_terms.calculation_period': 'ln_p_calculatPeriod',
  'loan_terms.seller_carry': 'ln_p_sellerCarry',
  'loan_terms.aitd_wrap': 'ln_p_aitdWrap',
  'loan_terms.cross_collateral': 'ln_p_crossCollat',
  'loan_terms.unsecured': 'ln_p_unsecure',
  'loan_terms.respa': 'ln_p_respa',
  'loan_terms.balloon_payment': 'ln_p_balloonPaymen',
  'loan_terms.parent_account': 'ln_p_parentAccoun',
  'loan_terms.child_account': 'ln_p_childAccoun',

  // LOAN TERMS PENALTIES
  'loan_terms.prepayment_penalty': 'ln_pn_prepaymePenalt',
  'loan_terms.prepayment_penalty_expires': 'ln_pn_prepaymePenaltExpire',
  'loan_terms.prepayment_penalty_and_privilege': 'ln_pn_prepaymePenaltAndPrivil',

  // ──────────────────────────────────────────────────
  // PROPERTY
  // ──────────────────────────────────────────────────
  'property1.description': 'pr_p_descript',
  'property1.street': 'pr_p_street',
  'property1.city': 'pr_p_city',
  'property1.state': 'pr_p_state',
  'property1.zip': 'pr_p_zip',
  'property1.county': 'pr_p_county',
  'property1.copy_borrower_address': 'pr_p_copyBorrowAddres',
  'property1.primary_property': 'pr_p_primaryProper',
  'property1.appraisal_performed_by': 'pr_p_performeBy',
  'property1.appraisal_property_type': 'pr_p_propertyType',
  'property1.appraisal_occupancy': 'pr_p_occupanc',
  'property1.ltv': 'pr_p_ltv',
  'property1.zoning': 'pr_p_zoning',
  'property1.appraised_value': 'pr_p_appraiseValue',
  'property1.pledged_equity': 'pr_p_pledgedEquity',
  'property1.appraised_date': 'pr_p_appraiseDate',
  'property1.priority': 'pr_p_priorit',
  'property1.flood_zone': 'pr_p_floodZone',
  'property1.apn': 'pr_p_apn',
  'property1.purchase_price': 'pr_p_purchasePrice',
  'property1.down_payment': 'pr_p_downPayme',
  'property1.delinquent_taxes': 'pr_p_delinquTaxes',
  'property1.appraiser_street': 'pr_p_appraiserStreet',
  'property1.appraiser_city': 'pr_p_appraiserCity',
  'property1.appraiser_state': 'pr_p_appraiserState',
  'property1.appraiser_zip': 'pr_p_appraiserZip',
  'property1.appraiser_phone': 'pr_p_appraiserPhone',
  'property1.appraiser_email': 'pr_p_appraiserEmail',
  'property1.year_built': 'pr_p_yearBuilt',
  'property1.square_feet': 'pr_p_squareFeet',
  'property1.construction_type': 'pr_p_construcType',
  'property1.monthly_income': 'pr_p_monthlyIncome',
  'property1.lien_protective_equity': 'pr_p_lienProtecEquity',
  'property1.source_lien_info': 'pr_p_sourceLienInfo',

  // PROPERTY LEGAL
  'property1.legal_description': 'pr_lg_legalDescri',
  'property1.lot': 'pr_lg_lot',
  'property1.block': 'pr_p_block',
  'property1.tract': 'pr_lg_tract',

  // PROPERTY INSURANCE
  'property1.insurance_description': 'pr_p_descript2',
  'property1.insured_s_name': 'pr_p_insuredName',
  'property1.insurance_company_name': 'pr_p_companyName',
  'property1.insurance_policy_number': 'pr_ins_insurancPolicyNumber',
  'property1.insurance_expiration': 'pr_p_expirati',
  'property1.insurance_coverage': 'pr_p_coverage',
  'property1.insurance_active': 'pr_p_active',
  'property1.agent_s_name': 'pr_p_agentsName',
  'property1.insurance_business_address': 'pr_p_businessAddres',
  'property1.insurance_phone_number': 'pr_p_insurancPhoneNumber',
  'property1.insurance_fax_number': 'pr_p_faxNumber',
  'property1.insurance_e_mail': 'pr_p_email',

  // PROPERTY LIENS
  'property1.lien_property': 'pr_li_lienProper',
  'property1.lien_priority': 'pr_li_lienPriori',
  'property1.lien_holder': 'pr_li_lienHolder',
  'property1.lien_account': 'pr_li_lienAccoun',
  'property1.lien_contact': 'pr_li_lienContac',
  'property1.lien_phone': 'pr_li_lienPhone',
  'property1.lien_original_balance': 'pr_li_lienOriginBalanc',
  'property1.lien_current_balance': 'pr_li_lienCurrenBalanc',
  'property1.lien_regular_payment': 'pr_li_lienRegulaPaymen',
  'property1.lien_last_checked': 'pr_li_lienLastChecke',

  // PROPERTY TAX
  'property1.tax.payee': 'pr_p_taxPayee',
  'property1.tax.payee_address': 'pr_p_taxPayeeAddres',
  'property1.tax.next_due_date': 'pr_p_taxNextDueDate',
  'property1.tax.frequency': 'pr_p_taxFreque',
  'property1.tax.hold': 'pr_p_taxHold',
  'property1.tax.ref': 'pr_p_taxRef',
  'property1.tax.memo': 'pr_p_taxMemo',
  'property1.tax.type': 'pr_p_taxType',
  'property1.tax.authority': 'pr_p_authorit',
  'property1.tax.tax_tracking': 'pr_p_taxTracki',
  'property1.tax.last_verified': 'pr_p_taxLastVerifi',
  'property1.tax.tracking_status': 'pr_p_taxTrackiStatus',

  // ──────────────────────────────────────────────────
  // BROKER
  // ──────────────────────────────────────────────────
  'broker.id': 'bk_p_brokerId',
  'broker.License': 'bk_p_brokerLicens',
  'broker.company': 'bk_p_company',
  'broker.first_name': 'bk_p_firstName',
  'broker.middle_name': 'bk_p_middleName',
  'broker.last_name': 'bk_p_lastName',
  'broker.email': 'bk_p_email',
  'broker.address.street': 'bk_p_street',
  'broker.address.city': 'bk_p_city',
  'broker.address.state': 'bk_p_state',
  'broker.address.zip': 'bk_p_zip',
  'broker.tax_id_type': 'bk_p_taxIdType',
  'broker.tax_id': 'bk_p_taxId',
  'broker.issue_1099': 'bk_p_issue1099',
  'broker.phone.home': 'bk_p_homePhone',
  'broker.phone.work': 'bk_p_workPhone',
  'broker.phone.cell': 'bk_p_cellPhone',
  'broker.phone.fax': 'bk_p_fax',
  'broker.preferred.home': 'bk_p_preferreHomePhone',
  'broker.preferred.work': 'bk_p_preferreWorkPhone',
  'broker.preferred.cell': 'bk_p_preferreCellPhone',
  'broker.preferred.fax': 'bk_p_preferreFax',
  'broker.send_pref.payment_notification': 'bk_p_paymentNotifi',
  'broker.send_pref.late_notice': 'bk_p_lateNotice',
  'broker.send_pref.lender_statement': 'bk_p_lenderStatem',
  'broker.send_pref.borrower_statement': 'bk_p_borrowerStatem',
  'broker.send_pref.maturity_notice': 'bk_p_maturityNotice',

  // BROKER BANKING
  'broker.banking.ach_status': 'bk_p_achStatus',
  'broker.banking.bank': 'bk_p_bank',
  'broker.banking.routing_number': 'bk_b_routingNumber',
  'broker.banking.account_number': 'bk_p_accountNumber',
  'broker.banking.account_type': 'bk_p_accountType',
  'broker.banking.account_name': 'bk_p_accountName',
  'broker.banking.account_id': 'bk_p_accountId',
  'broker.banking.further_credit_to': 'bk_p_furtherCreditTo',
  'broker.banking.by_check': 'bk_p_byCheck',
  'broker.banking.check_same_as_mailing': 'bk_p_sameAsMailin',
  'broker.banking.check_address': 'bk_p_checkAddres',
  'broker.banking.check_city': 'bk_p_checkCity',
  'broker.banking.check_zip': 'bk_p_checkZip',
  'broker.banking.ach_email': 'bk_p_achEmail',
  'broker.banking.cc_name': 'bk_p_creditCardName',
  'broker.banking.cc_number': 'bk_p_cardNumber',
  'broker.banking.cc_security_code': 'bk_p_securityCode',
  'broker.banking.cc_expiration': 'bk_p_expirati',
  'broker.banking.cc_zip': 'bk_p_creditCardZip',

  // ──────────────────────────────────────────────────
  // CHARGES
  // ──────────────────────────────────────────────────
  'charge.description': 'ch_p_descript',
  'charge.unpaid_balance': 'ch_p_unpaidBalanc',
  'charge.owed_to': 'ch_p_owedToAccoun',
  'charge.total_due': 'ch_p_totalDue',
  'charge.interest_from': 'ch_p_interestFrom',
  'charge.date_of_charge': 'ch_p_dateOfCharge',
  'charge.interest_rate': 'ch_p_interestRate',
  'charge.notes': 'ch_p_notes',
  'charge.reference': 'ch_p_referenc',
  'charge.charge_type': 'ch_p_chargeType',
  'charge.deferred': 'ch_p_deferred',
  'charge.original_amount': 'ch_p_originalAmount',
  'charge.account': 'ch_p_account',
  'charge.borrower_full_name': 'ch_p_borrowerFullName',
  'charge.advanced_by_account': 'ch_p_advancedByAccoun',
  'charge.advanced_by_lender_name': 'ch_p_advancedByLenderName',
  'charge.advanced_by_amount': 'ch_p_advancedByAmount',
  'charge.on_behalf_of_account': 'ch_p_onBehalfOfAccoun',
  'charge.on_behalf_of_lender_name': 'ch_p_onBehalfOfLender',
  'charge.on_behalf_of_amount': 'ch_p_onBehalfOfAmount',
  'charge.amount_owed_by_borrower': 'ch_p_amountOwedByBorrow',
  'charge.accrued_interest': 'ch_p_accruedIntere',

  // Also map the charge_ dictionary keys used in CHARGE_UI_TO_DICT
  'charges.description': 'ch_p_descript',
  'charges.unpaid_balance': 'ch_p_unpaidBalanc',
  'charges.owed_to': 'ch_p_owedToAccoun',
  'charges.total_due': 'ch_p_totalDue',
  'charges.interest_from': 'ch_p_interestFrom',
  'charges.date_of_charge': 'ch_p_dateOfCharge',
  'charges.interest_rate': 'ch_p_interestRate',
  'charges.notes': 'ch_p_notes',
  'charges.reference': 'ch_p_referenc',
  'charges.charge_type': 'ch_p_chargeType',
  'charges.deferred': 'ch_p_deferred',
  'charges.original_amount': 'ch_p_originalAmount',
  'charges.account': 'ch_p_account',
  'charges.borrower_full_name': 'ch_p_borrowerFullName',
  'charges.advanced_by_account': 'ch_p_advancedByAccoun',
  'charges.advanced_by_lender_name': 'ch_p_advancedByLenderName',
  'charges.advanced_by_amount': 'ch_p_advancedByAmount',
  'charges.on_behalf_of_account': 'ch_p_onBehalfOfAccoun',
  'charges.on_behalf_of_lender_name': 'ch_p_onBehalfOfLender',
  'charges.on_behalf_of_amount': 'ch_p_onBehalfOfAmount',
  'charges.amount_owed_by_borrower': 'ch_p_amountOwedByBorrow',
  'charges.accrued_interest': 'ch_p_accruedIntere',
  'charges.owed_from': 'ch_p_owedFrom',
  'charges.distribute_between_all_lenders': 'ch_p_distribuBetweenAll',

  // Charge dictionary format keys (used by CHARGE_UI_TO_DICT reverse mapping)
  'charge_date': 'ch_p_dateOfCharge',
  'charge_description': 'ch_p_descript',
  'charge_interest_rate': 'ch_p_interestRate',
  'charge_interest_start_date': 'ch_p_interestFrom',
  'charge_reference': 'ch_p_referenc',
  'charge_type': 'ch_p_chargeType',
  'charge_notes': 'ch_p_notes',
  'charge_original_amount': 'ch_p_originalAmount',
  'charge_is_deferred': 'ch_p_deferred',
  'charge_accrued_interest': 'ch_p_accruedIntere',
  'charge_unpaid_balance': 'ch_p_unpaidBalanc',
  'charge_total_due': 'ch_p_totalDue',
  'charge_owed_to': 'ch_p_owedToAccoun',
  'charge_account': 'ch_p_account',
  'charge_borrower_full_name': 'ch_p_borrowerFullName',
  'charge_advanced_by_account': 'ch_p_advancedByAccoun',
  'charge_advanced_by_lender_name': 'ch_p_advancedByLenderName',
  'charge_advanced_by_amount': 'ch_p_advancedByAmount',
  'charge_on_behalf_of_account': 'ch_p_onBehalfOfAccoun',
  'charge_on_behalf_of_lender_name': 'ch_p_onBehalfOfLender',
  'charge_on_behalf_of_amount': 'ch_p_onBehalfOfAmount',
  'charge_amount_owed_by_borrower': 'ch_p_amountOwedByBorrow',
};

// Build reverse map: DB key → legacy key (for hydration)
export const DB_KEY_TO_LEGACY: Record<string, string> = {};
// Only map the first (canonical) legacy key for each DB key
const _seenDbKeys = new Set<string>();
for (const [legacy, db] of Object.entries(LEGACY_TO_DB_KEY)) {
  if (!_seenDbKeys.has(db)) {
    DB_KEY_TO_LEGACY[db] = legacy;
    _seenDbKeys.add(db);
  }
}

/**
 * Resolve a legacy dot-notation key to its DB field_key.
 * Returns the DB key if found, otherwise the original key unchanged.
 */
export function resolveLegacyKey(legacyKey: string): string {
  return LEGACY_TO_DB_KEY[legacyKey] || legacyKey;
}

/**
 * Resolve a DB field_key back to its legacy dot-notation key.
 * Returns the legacy key if found, otherwise the original key unchanged.
 */
export function resolveDbKeyToLegacy(dbKey: string): string {
  return DB_KEY_TO_LEGACY[dbKey] || dbKey;
}
