project_id = "rdnefvczlzsdoijdvoxt"

[functions.generate-document]
verify_jwt = false

[functions.validate-template]
verify_jwt = false

[functions.send-message]
verify_jwt = false

[functions.migrate-field-keys]
verify_jwt = false
