
INSERT INTO field_dictionary (field_key, label, section, data_type) VALUES
-- Override
('loan_terms.servicing.override', 'Override', 'loan_terms', 'boolean'),
-- Standard Servicing
('loan_terms.servicing.standard_servicing.enabled', 'Standard Servicing Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.standard_servicing.cost', 'Standard Servicing Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.standard_servicing.lender_percent', 'Standard Servicing Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.standard_servicing.lenders_split', 'Standard Servicing Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.standard_servicing.borrower_amount', 'Standard Servicing Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.standard_servicing.borrower_percent', 'Standard Servicing Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.standard_servicing.broker', 'Standard Servicing Broker', 'loan_terms', 'text'),
-- High Touch
('loan_terms.servicing.high_touch.enabled', 'High Touch Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.high_touch.cost', 'High Touch Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.high_touch.lender_percent', 'High Touch Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.high_touch.lenders_split', 'High Touch Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.high_touch.borrower_amount', 'High Touch Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.high_touch.borrower_percent', 'High Touch Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.high_touch.broker', 'High Touch Broker', 'loan_terms', 'text'),
-- Default
('loan_terms.servicing.default.enabled', 'Default Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.default.cost', 'Default Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.default.lender_percent', 'Default Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.default.lenders_split', 'Default Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.default.borrower_amount', 'Default Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.default.borrower_percent', 'Default Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.default.broker', 'Default Broker', 'loan_terms', 'text'),
-- Minimum Fee
('loan_terms.servicing.minimum_fee.enabled', 'Minimum Fee Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.minimum_fee.cost', 'Minimum Fee Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.minimum_fee.lender_percent', 'Minimum Fee Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.minimum_fee.lenders_split', 'Minimum Fee Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.minimum_fee.borrower_amount', 'Minimum Fee Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.minimum_fee.borrower_percent', 'Minimum Fee Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.minimum_fee.broker', 'Minimum Fee Broker', 'loan_terms', 'text'),
-- Minimum Per Lender
('loan_terms.servicing.minimum_per_lender.enabled', 'Minimum Per Lender Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.minimum_per_lender.cost', 'Minimum Per Lender Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.minimum_per_lender.lender_percent', 'Minimum Per Lender Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.minimum_per_lender.lenders_split', 'Minimum Per Lender Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.minimum_per_lender.borrower_amount', 'Minimum Per Lender Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.minimum_per_lender.borrower_percent', 'Minimum Per Lender Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.minimum_per_lender.broker', 'Minimum Per Lender Broker', 'loan_terms', 'text'),
-- CALFIRPTA
('loan_terms.servicing.calfirpta.enabled', 'CALFIRPTA Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.calfirpta.cost', 'CALFIRPTA Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.calfirpta.lender_percent', 'CALFIRPTA Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.calfirpta.lenders_split', 'CALFIRPTA Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.calfirpta.borrower_amount', 'CALFIRPTA Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.calfirpta.borrower_percent', 'CALFIRPTA Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.calfirpta.broker', 'CALFIRPTA Broker', 'loan_terms', 'text'),
-- Escrow Impound
('loan_terms.servicing.escrow_impound.enabled', 'Escrow Impound Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.escrow_impound.cost', 'Escrow Impound Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.escrow_impound.lender_percent', 'Escrow Impound Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.escrow_impound.lenders_split', 'Escrow Impound Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.escrow_impound.borrower_amount', 'Escrow Impound Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.escrow_impound.borrower_percent', 'Escrow Impound Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.escrow_impound.broker', 'Escrow Impound Broker', 'loan_terms', 'text'),
-- Insurance Tracking
('loan_terms.servicing.insurance_tracking.enabled', 'Insurance Tracking Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.insurance_tracking.cost', 'Insurance Tracking Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.insurance_tracking.lender_percent', 'Insurance Tracking Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.insurance_tracking.lenders_split', 'Insurance Tracking Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.insurance_tracking.borrower_amount', 'Insurance Tracking Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.insurance_tracking.borrower_percent', 'Insurance Tracking Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.insurance_tracking.broker', 'Insurance Tracking Broker', 'loan_terms', 'text'),
-- Tax Tracking
('loan_terms.servicing.tax_tracking.enabled', 'Tax Tracking Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.tax_tracking.cost', 'Tax Tracking Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.tax_tracking.lender_percent', 'Tax Tracking Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.tax_tracking.lenders_split', 'Tax Tracking Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.tax_tracking.borrower_amount', 'Tax Tracking Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.tax_tracking.borrower_percent', 'Tax Tracking Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.tax_tracking.broker', 'Tax Tracking Broker', 'loan_terms', 'text'),
-- Senior Lien Tracking
('loan_terms.servicing.senior_lien_tracking.enabled', 'Senior Lien Tracking Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.senior_lien_tracking.cost', 'Senior Lien Tracking Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.senior_lien_tracking.lender_percent', 'Senior Lien Tracking Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.senior_lien_tracking.lenders_split', 'Senior Lien Tracking Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.senior_lien_tracking.borrower_amount', 'Senior Lien Tracking Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.senior_lien_tracking.borrower_percent', 'Senior Lien Tracking Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.senior_lien_tracking.broker', 'Senior Lien Tracking Broker', 'loan_terms', 'text'),
-- Additional Disbursements
('loan_terms.servicing.additional_disbursements.enabled', 'Additional Disbursements Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.additional_disbursements.cost', 'Additional Disbursements Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.additional_disbursements.lender_percent', 'Additional Disbursements Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.additional_disbursements.lenders_split', 'Additional Disbursements Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.additional_disbursements.borrower_amount', 'Additional Disbursements Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.additional_disbursements.borrower_percent', 'Additional Disbursements Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.additional_disbursements.broker', 'Additional Disbursements Broker', 'loan_terms', 'text'),
-- Document Storage
('loan_terms.servicing.document_storage.enabled', 'Document Storage Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.document_storage.cost', 'Document Storage Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.document_storage.lender_percent', 'Document Storage Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.document_storage.lenders_split', 'Document Storage Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.document_storage.borrower_amount', 'Document Storage Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.document_storage.borrower_percent', 'Document Storage Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.document_storage.broker', 'Document Storage Broker', 'loan_terms', 'text'),
-- Mail
('loan_terms.servicing.mail.enabled', 'Mail Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.mail.cost', 'Mail Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.mail.lender_percent', 'Mail Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.mail.lenders_split', 'Mail Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.mail.borrower_amount', 'Mail Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.mail.borrower_percent', 'Mail Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.mail.broker', 'Mail Broker', 'loan_terms', 'text'),
-- Reserve Pass Through
('loan_terms.servicing.reserve_pass_through.enabled', 'Reserve Pass Through Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.reserve_pass_through.cost', 'Reserve Pass Through Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.reserve_pass_through.lender_percent', 'Reserve Pass Through Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.reserve_pass_through.lenders_split', 'Reserve Pass Through Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.reserve_pass_through.borrower_amount', 'Reserve Pass Through Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.reserve_pass_through.borrower_percent', 'Reserve Pass Through Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.reserve_pass_through.broker', 'Reserve Pass Through Broker', 'loan_terms', 'text'),
-- Reserve Hold and Pay
('loan_terms.servicing.reserve_hold_and_pay.enabled', 'Reserve Hold and Pay Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.reserve_hold_and_pay.cost', 'Reserve Hold and Pay Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.reserve_hold_and_pay.lender_percent', 'Reserve Hold and Pay Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.reserve_hold_and_pay.lenders_split', 'Reserve Hold and Pay Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.reserve_hold_and_pay.borrower_amount', 'Reserve Hold and Pay Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.reserve_hold_and_pay.borrower_percent', 'Reserve Hold and Pay Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.reserve_hold_and_pay.broker', 'Reserve Hold and Pay Broker', 'loan_terms', 'text'),
-- Late Notice
('loan_terms.servicing.late_notice.enabled', 'Late Notice Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.late_notice.cost', 'Late Notice Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.late_notice.lender_percent', 'Late Notice Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.late_notice.lenders_split', 'Late Notice Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.late_notice.borrower_amount', 'Late Notice Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.late_notice.borrower_percent', 'Late Notice Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.late_notice.broker', 'Late Notice Broker', 'loan_terms', 'text'),
-- Buyer Notice
('loan_terms.servicing.buyer_notice.enabled', 'Buyer Notice Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.buyer_notice.cost', 'Buyer Notice Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.buyer_notice.lender_percent', 'Buyer Notice Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.buyer_notice.lenders_split', 'Buyer Notice Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.buyer_notice.borrower_amount', 'Buyer Notice Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.buyer_notice.borrower_percent', 'Buyer Notice Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.buyer_notice.broker', 'Buyer Notice Broker', 'loan_terms', 'text'),
-- Seller Notice
('loan_terms.servicing.seller_notice.enabled', 'Seller Notice Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.seller_notice.cost', 'Seller Notice Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.seller_notice.lender_percent', 'Seller Notice Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.seller_notice.lenders_split', 'Seller Notice Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.seller_notice.borrower_amount', 'Seller Notice Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.seller_notice.borrower_percent', 'Seller Notice Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.seller_notice.broker', 'Seller Notice Broker', 'loan_terms', 'text'),
-- 3rd Party Notice
('loan_terms.servicing.third_party_notice.enabled', '3rd Party Notice Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.third_party_notice.cost', '3rd Party Notice Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.third_party_notice.lender_percent', '3rd Party Notice Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.third_party_notice.lenders_split', '3rd Party Notice Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.third_party_notice.borrower_amount', '3rd Party Notice Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.third_party_notice.borrower_percent', '3rd Party Notice Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.third_party_notice.broker', '3rd Party Notice Broker', 'loan_terms', 'text'),
-- Custom row
('loan_terms.servicing.custom.label', 'Custom Service Label', 'loan_terms', 'text'),
('loan_terms.servicing.custom.enabled', 'Custom Service Enabled', 'loan_terms', 'boolean'),
('loan_terms.servicing.custom.cost', 'Custom Service Cost', 'loan_terms', 'currency'),
('loan_terms.servicing.custom.lender_percent', 'Custom Service Lender %', 'loan_terms', 'percentage'),
('loan_terms.servicing.custom.lenders_split', 'Custom Service Lenders Split', 'loan_terms', 'text'),
('loan_terms.servicing.custom.borrower_amount', 'Custom Service Borrower $', 'loan_terms', 'currency'),
('loan_terms.servicing.custom.borrower_percent', 'Custom Service Borrower %', 'loan_terms', 'percentage'),
('loan_terms.servicing.custom.broker', 'Custom Service Broker', 'loan_terms', 'text')
ON CONFLICT (field_key) DO NOTHING;
