-- Add new section enum values for Loan Charges History, Properties, Customize Grid, New Property, and Trust Ledger
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'loan_charges_history_header';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'loan_charges_history_summary';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'loan_charges_history_transactions';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'loan_charges_toolbar';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'properties_main_grid';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'properties_eds';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'customize_grid_config';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'customize_grid_actions';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'new_property_address';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'new_property_appraisal';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'new_property_legal';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'new_property_tabs';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'new_property_actions';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'new_property_dropdowns';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'trust_ledger_tabs';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'trust_ledger_filters';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'trust_ledger_grid';
ALTER TYPE field_section ADD VALUE IF NOT EXISTS 'trust_ledger_toolbar';