INSERT INTO field_dictionary (field_key, label, section, data_type, is_calculated, is_repeatable) VALUES
-- Late Fee I
('loan_terms.penalties.late_charge_1.enabled', 'Late Fee I Enabled', 'loan_terms', 'boolean', false, false),
('loan_terms.penalties.late_charge_1.calendar_actual', 'Late Fee I Calendar/Actual', 'loan_terms', 'text', false, false),
('loan_terms.penalties.late_charge_1.minimum_late_fee', 'Late Fee I Minimum', 'loan_terms', 'currency', false, false),
('loan_terms.penalties.late_charge_1.percentage_of_payment', 'Late Fee I Percentage', 'loan_terms', 'percentage', false, false),
('loan_terms.penalties.late_charge_1.additional_daily_charge', 'Late Fee I Additional Daily', 'loan_terms', 'currency', false, false),
('loan_terms.penalties.late_charge_1.distribution.lenders', 'Late Fee I Dist Lenders', 'loan_terms', 'text', false, false),
('loan_terms.penalties.late_charge_1.distribution.origination_vendors', 'Late Fee I Dist Orig Vendors', 'loan_terms', 'text', false, false),
('loan_terms.penalties.late_charge_1.distribution.company', 'Late Fee I Dist Company', 'loan_terms', 'text', false, false),
('loan_terms.penalties.late_charge_1.distribution.other', 'Late Fee I Dist Other', 'loan_terms', 'text', false, false),
-- Late Fee II
('loan_terms.penalties.late_charge_2.type', 'Late Fee II Type', 'loan_terms', 'text', false, false),
('loan_terms.penalties.late_charge_2.calendar_actual', 'Late Fee II Calendar/Actual', 'loan_terms', 'text', false, false),
('loan_terms.penalties.late_charge_2.minimum_late_fee', 'Late Fee II Minimum', 'loan_terms', 'currency', false, false),
('loan_terms.penalties.late_charge_2.percentage_of_payment', 'Late Fee II Percentage', 'loan_terms', 'percentage', false, false),
('loan_terms.penalties.late_charge_2.additional_daily_charge', 'Late Fee II Additional Daily', 'loan_terms', 'currency', false, false),
('loan_terms.penalties.late_charge_2.distribution.lenders', 'Late Fee II Dist Lenders', 'loan_terms', 'text', false, false),
('loan_terms.penalties.late_charge_2.distribution.origination_vendors', 'Late Fee II Dist Orig Vendors', 'loan_terms', 'text', false, false),
('loan_terms.penalties.late_charge_2.distribution.company', 'Late Fee II Dist Company', 'loan_terms', 'text', false, false),
('loan_terms.penalties.late_charge_2.distribution.other', 'Late Fee II Dist Other', 'loan_terms', 'text', false, false),
-- Default Interest
('loan_terms.penalties.default_interest.triggered_by', 'Default Interest Triggered By', 'loan_terms', 'text', false, false),
('loan_terms.penalties.default_interest.flat_rate_enabled', 'Default Interest Flat Rate Enabled', 'loan_terms', 'boolean', false, false),
('loan_terms.penalties.default_interest.modifier_enabled', 'Default Interest Modifier Enabled', 'loan_terms', 'boolean', false, false),
('loan_terms.penalties.default_interest.modifier', 'Default Interest Modifier', 'loan_terms', 'percentage', false, false),
('loan_terms.penalties.default_interest.active_until', 'Default Interest Active Until', 'loan_terms', 'date', false, false),
('loan_terms.penalties.default_interest.additional_daily_charge', 'Default Interest Additional Daily', 'loan_terms', 'currency', false, false),
('loan_terms.penalties.default_interest.distribution.other', 'Default Interest Dist Other', 'loan_terms', 'text', false, false),
-- Interest Guarantee
('loan_terms.penalties.interest_guarantee.enabled', 'Interest Guarantee Enabled', 'loan_terms', 'boolean', false, false),
('loan_terms.penalties.interest_guarantee.months_enabled', 'Interest Guarantee Months Enabled', 'loan_terms', 'boolean', false, false),
('loan_terms.penalties.interest_guarantee.months', 'Interest Guarantee Months', 'loan_terms', 'number', false, false),
('loan_terms.penalties.interest_guarantee.include_odd_days', 'Interest Guarantee Include Odd Days', 'loan_terms', 'boolean', false, false),
('loan_terms.penalties.interest_guarantee.amount_enabled', 'Interest Guarantee Amount Enabled', 'loan_terms', 'boolean', false, false),
('loan_terms.penalties.interest_guarantee.amount', 'Interest Guarantee Amount', 'loan_terms', 'currency', false, false),
('loan_terms.penalties.interest_guarantee.distribution.lenders', 'Interest Guarantee Dist Lenders', 'loan_terms', 'text', false, false),
('loan_terms.penalties.interest_guarantee.distribution.origination_vendors', 'Interest Guarantee Dist Orig Vendors', 'loan_terms', 'text', false, false),
('loan_terms.penalties.interest_guarantee.distribution.company', 'Interest Guarantee Dist Company', 'loan_terms', 'text', false, false),
('loan_terms.penalties.interest_guarantee.distribution.other', 'Interest Guarantee Dist Other', 'loan_terms', 'text', false, false),
-- Prepayment
('loan_terms.penalties.prepayment.enabled', 'Prepayment Penalty Enabled', 'loan_terms', 'boolean', false, false),
('loan_terms.penalties.prepayment.first_years', 'Prepayment First Years', 'loan_terms', 'number', false, false),
('loan_terms.penalties.prepayment.greater_than', 'Prepayment Greater Than', 'loan_terms', 'percentage', false, false),
('loan_terms.penalties.prepayment.distribution.lenders', 'Prepayment Dist Lenders', 'loan_terms', 'text', false, false),
('loan_terms.penalties.prepayment.distribution.origination_vendors', 'Prepayment Dist Orig Vendors', 'loan_terms', 'text', false, false),
('loan_terms.penalties.prepayment.distribution.company', 'Prepayment Dist Company', 'loan_terms', 'text', false, false),
('loan_terms.penalties.prepayment.distribution.other', 'Prepayment Dist Other', 'loan_terms', 'text', false, false),
-- Maturity
('loan_terms.penalties.maturity.enabled', 'Maturity Penalty Enabled', 'loan_terms', 'boolean', false, false),
('loan_terms.penalties.maturity.standard_10_percent', 'Maturity Standard 10% Payment', 'loan_terms', 'boolean', false, false),
('loan_terms.penalties.maturity.additional_flat_fee_enabled', 'Maturity Additional Flat Fee Enabled', 'loan_terms', 'boolean', false, false),
('loan_terms.penalties.maturity.additional_flat_fee', 'Maturity Additional Flat Fee', 'loan_terms', 'currency', false, false),
('loan_terms.penalties.maturity.distribution.lenders', 'Maturity Dist Lenders', 'loan_terms', 'text', false, false),
('loan_terms.penalties.maturity.distribution.origination_vendors', 'Maturity Dist Orig Vendors', 'loan_terms', 'text', false, false),
('loan_terms.penalties.maturity.distribution.company', 'Maturity Dist Company', 'loan_terms', 'text', false, false),
('loan_terms.penalties.maturity.distribution.other', 'Maturity Dist Other', 'loan_terms', 'text', false, false)
ON CONFLICT (field_key) DO NOTHING;