INSERT INTO field_dictionary (field_key, label, section, data_type, is_calculated, is_repeatable)
VALUES
  ('of_re_proposedLoanAmount', 'Proposed Loan Amount', 'origination_fees', 'currency', false, false),
  ('of_re_initialFeesPage1', 'Initial Fees Page 1', 'origination_fees', 'currency', false, false),
  ('of_re_otherObligations', 'Other Obligations', 'origination_fees', 'currency', false, false),
  ('of_re_creditLifeInsurance', 'Credit Life Insurance', 'origination_fees', 'currency', false, false),
  ('of_re_additionalObligation1', 'Additional Obligation 1', 'origination_fees', 'currency', false, false),
  ('of_re_additionalObligation2', 'Additional Obligation 2', 'origination_fees', 'currency', false, false),
  ('of_re_subtotalDeductions', 'Subtotal Deductions', 'origination_fees', 'currency', true, false),
  ('of_re_cashAtClosingOption', 'Cash at Closing Option', 'origination_fees', 'text', false, false),
  ('of_re_cashAtClosingAmount', 'Cash at Closing Amount', 'origination_fees', 'currency', true, false),
  ('of_re_loanTermValue', 'Loan Term Value', 'origination_fees', 'integer', false, false),
  ('of_re_loanTermUnit', 'Loan Term Unit', 'origination_fees', 'text', false, false),
  ('of_re_interestRate', 'Interest Rate', 'origination_fees', 'percentage', false, false),
  ('of_re_rateTypeFixed', 'Rate Type Fixed', 'origination_fees', 'boolean', false, false),
  ('of_re_rateTypeAdjustable', 'Rate Type Adjustable', 'origination_fees', 'boolean', false, false),
  ('of_re_ivAdjRateMonths', 'IV Adj Rate Months', 'origination_fees', 'integer', false, false),
  ('of_re_vFullyIndexedRate', 'V Fully Indexed Rate', 'origination_fees', 'percentage', false, false),
  ('of_re_viMaxInterestRate', 'VI Max Interest Rate', 'origination_fees', 'percentage', false, false),
  ('of_re_viiPaymentAmount', 'VII Payment Amount', 'origination_fees', 'currency', false, false),
  ('of_re_viiiRateIncreasePct', 'VIII Rate Increase Pct', 'origination_fees', 'percentage', false, false),
  ('of_re_viiiRateIncreaseMonths', 'VIII Rate Increase Months', 'origination_fees', 'integer', false, false),
  ('of_re_ixPaymentEndMonths', 'IX Payment End Months', 'origination_fees', 'integer', false, false),
  ('of_re_ixPaymentEndPct', 'IX Payment End Pct', 'origination_fees', 'percentage', false, false),
  ('of_re_xiNegAmortBalance', 'XI Neg Amort Balance', 'origination_fees', 'currency', false, false),
  ('of_re_impoundCountyTaxes', 'Impound County Taxes', 'origination_fees', 'boolean', false, false),
  ('of_re_impoundHazardIns', 'Impound Hazard Insurance', 'origination_fees', 'boolean', false, false),
  ('of_re_impoundMortgageIns', 'Impound Mortgage Insurance', 'origination_fees', 'boolean', false, false),
  ('of_re_impoundFloodIns', 'Impound Flood Insurance', 'origination_fees', 'boolean', false, false),
  ('of_re_impoundOther', 'Impound Other', 'origination_fees', 'boolean', false, false),
  ('of_re_impoundOtherDesc', 'Impound Other Description', 'origination_fees', 'text', false, false),
  ('of_re_impoundApproxAmount', 'Impound Approx Amount', 'origination_fees', 'currency', false, false);